(() => {
  const routes = [
    {id:'new',path:'/nouveautes',group:'commerce',type:'category'},
    {id:'women',path:'/femme',group:'commerce',type:'category'},
    {id:'men',path:'/homme',group:'commerce',type:'category'},
    {id:'kids',path:'/enfant',group:'commerce',type:'category'},
    {id:'sport',path:'/sport',group:'commerce',type:'category'},
    {id:'accessories',path:'/accessoires',group:'commerce',type:'category'},
    {id:'beauty',path:'/beaute',group:'commerce',type:'category'},
    {id:'sale',path:'/soldes',group:'commerce',type:'category'},
    {id:'search',path:'/recherche',group:'commerce',type:'search'},
    {id:'product',pattern:'^/produit/[^/]+$',group:'commerce',type:'product'},
    {id:'corners',path:'/corners',group:'commerce',type:'corners'},
    {id:'corner',pattern:'^/corner/[^/]+$',group:'commerce',type:'corner'},
    {id:'privateSale',path:'/vente-privee',group:'commerce',type:'privateSale'},

    {id:'favourites',path:'/favoris',group:'customer',type:'favourites'},
    {id:'bag',path:'/panier',group:'customer',type:'bag'},
    {id:'login',path:'/connexion',group:'customer',type:'login'},
    {id:'account',path:'/compte',group:'customer',type:'account'},
    {id:'profile',path:'/compte/profil',group:'customer',type:'accountDetail'},
    {id:'addresses',path:'/compte/adresses',group:'customer',type:'accountDetail'},
    {id:'orders',path:'/compte/commandes',group:'customer',type:'orders'},
    {id:'order',pattern:'^/compte/commandes/[^/]+$',group:'customer',type:'order'},
    {id:'returns',path:'/compte/retours',group:'customer',type:'accountDetail'},
    {id:'tracking',path:'/compte/suivi',group:'customer',type:'tracking'},

    {id:'checkoutIdentify',path:'/checkout',group:'checkout',type:'checkout'},
    {id:'checkoutDelivery',path:'/checkout/livraison',group:'checkout',type:'checkout'},
    {id:'checkoutPayment',path:'/checkout/paiement',group:'checkout',type:'checkout'},
    {id:'checkoutReview',path:'/checkout/revision',group:'checkout',type:'checkout'},
    {id:'checkoutConfirmation',path:'/checkout/confirmation',group:'checkout',type:'checkout'},

    {id:'delivery',path:'/livraisons',group:'service',type:'service'},
    {id:'refunds',path:'/retours-remboursements',group:'service',type:'service'},
    {id:'help',path:'/aide',group:'service',type:'help'},
    {id:'contact',path:'/contact',group:'service',type:'contact'},

    {id:'legalNotice',path:'/mentions-legales',group:'legal',type:'legal'},
    {id:'termsSale',path:'/cgv',group:'legal',type:'legal'},
    {id:'termsUse',path:'/conditions-utilisation',group:'legal',type:'legal'},
    {id:'privacy',path:'/confidentialite',group:'legal',type:'legal'},
    {id:'cookies',path:'/cookies',group:'legal',type:'legal'},
    {id:'consent',path:'/consentement',group:'legal',type:'consent'}
  ];

  const titles = {
    fr:{new:'Nouveautés',women:'Femme',men:'Homme',kids:'Enfant',sport:'Sport',accessories:'Accessoires',beauty:'Beauté',sale:'Soldes',search:'Recherche',product:'Détail du produit',corners:'Corners',corner:'Boutique partenaire',privateSale:'Vente privée',favourites:'Favoris',bag:'Panier',login:'Connexion',account:'Mon compte',profile:'Profil',addresses:'Adresses',orders:'Commandes',order:'Détail de la commande',returns:'Retours',tracking:'Suivi de commande',checkoutIdentify:'Identification',checkoutDelivery:'Livraison',checkoutPayment:'Paiement',checkoutReview:'Révision de la commande',checkoutConfirmation:'Confirmation',delivery:'Livraisons',refunds:'Retours & remboursements',help:'Aide',contact:'Contact',legalNotice:'Mentions légales',termsSale:'Conditions Générales de Vente',termsUse:'Conditions d’utilisation',privacy:'Politique de confidentialité',cookies:'Politique de cookies',consent:'Gestion du consentement'},
    pt:{new:'Novidades',women:'Mulher',men:'Homem',kids:'Criança',sport:'Desporto',accessories:'Acessórios',beauty:'Beleza',sale:'Saldos',search:'Pesquisa',product:'Detalhe do produto',corners:'Corners',corner:'Boutique parceira',privateSale:'Venda privada',favourites:'Favoritos',bag:'Carrinho',login:'Entrar',account:'A minha conta',profile:'Perfil',addresses:'Moradas',orders:'Encomendas',order:'Detalhe da encomenda',returns:'Devoluções',tracking:'Seguir encomenda',checkoutIdentify:'Identificação',checkoutDelivery:'Entrega',checkoutPayment:'Pagamento',checkoutReview:'Revisão da encomenda',checkoutConfirmation:'Confirmação',delivery:'Entregas',refunds:'Devoluções e reembolsos',help:'Ajuda',contact:'Contacto',legalNotice:'Aviso legal',termsSale:'Condições Gerais de Venda',termsUse:'Condições de utilização',privacy:'Política de privacidade',cookies:'Política de cookies',consent:'Gestão de consentimento'},
    en:{new:'New arrivals',women:'Women',men:'Men',kids:'Kids',sport:'Sport',accessories:'Accessories',beauty:'Beauty',sale:'Sale',search:'Search',product:'Product detail',corners:'Corners',corner:'Partner boutique',privateSale:'Private sale',favourites:'Favourites',bag:'Bag',login:'Sign in',account:'My account',profile:'Profile',addresses:'Addresses',orders:'Orders',order:'Order detail',returns:'Returns',tracking:'Order tracking',checkoutIdentify:'Identification',checkoutDelivery:'Delivery',checkoutPayment:'Payment',checkoutReview:'Order review',checkoutConfirmation:'Confirmation',delivery:'Delivery',refunds:'Returns & refunds',help:'Help',contact:'Contact',legalNotice:'Legal notice',termsSale:'Terms of sale',termsUse:'Terms of use',privacy:'Privacy policy',cookies:'Cookie policy',consent:'Consent management'},
    es:{new:'Novedades',women:'Mujer',men:'Hombre',kids:'Niños',sport:'Deporte',accessories:'Accesorios',beauty:'Belleza',sale:'Rebajas',search:'Buscar',product:'Detalle del producto',corners:'Corners',corner:'Boutique colaboradora',privateSale:'Venta privada',favourites:'Favoritos',bag:'Carrito',login:'Acceder',account:'Mi cuenta',profile:'Perfil',addresses:'Direcciones',orders:'Pedidos',order:'Detalle del pedido',returns:'Devoluciones',tracking:'Seguimiento del pedido',checkoutIdentify:'Identificación',checkoutDelivery:'Entrega',checkoutPayment:'Pago',checkoutReview:'Revisión del pedido',checkoutConfirmation:'Confirmación',delivery:'Entregas',refunds:'Devoluciones y reembolsos',help:'Ayuda',contact:'Contacto',legalNotice:'Aviso legal',termsSale:'Condiciones Generales de Venta',termsUse:'Condiciones de uso',privacy:'Política de privacidad',cookies:'Política de cookies',consent:'Gestión del consentimiento'},
    it:{new:'Novità',women:'Donna',men:'Uomo',kids:'Bambini',sport:'Sport',accessories:'Accessori',beauty:'Beauty',sale:'Saldi',search:'Ricerca',product:'Dettaglio prodotto',corners:'Corners',corner:'Boutique partner',privateSale:'Vendita privata',favourites:'Preferiti',bag:'Carrello',login:'Accedi',account:'Il mio account',profile:'Profilo',addresses:'Indirizzi',orders:'Ordini',order:'Dettaglio ordine',returns:'Resi',tracking:'Tracciamento ordine',checkoutIdentify:'Identificazione',checkoutDelivery:'Consegna',checkoutPayment:'Pagamento',checkoutReview:'Riepilogo ordine',checkoutConfirmation:'Conferma',delivery:'Consegne',refunds:'Resi e rimborsi',help:'Aiuto',contact:'Contatti',legalNotice:'Note legali',termsSale:'Condizioni Generali di Vendita',termsUse:'Condizioni d’uso',privacy:'Informativa sulla privacy',cookies:'Politica sui cookie',consent:'Gestione del consenso'},
    de:{new:'Neuheiten',women:'Damen',men:'Herren',kids:'Kinder',sport:'Sport',accessories:'Accessoires',beauty:'Beauty',sale:'Sale',search:'Suche',product:'Produktdetails',corners:'Corners',corner:'Partner-Boutique',privateSale:'Private Sale',favourites:'Favoriten',bag:'Warenkorb',login:'Anmelden',account:'Mein Konto',profile:'Profil',addresses:'Adressen',orders:'Bestellungen',order:'Bestelldetails',returns:'Rücksendungen',tracking:'Sendungsverfolgung',checkoutIdentify:'Identifikation',checkoutDelivery:'Lieferung',checkoutPayment:'Zahlung',checkoutReview:'Bestellprüfung',checkoutConfirmation:'Bestätigung',delivery:'Lieferung',refunds:'Rücksendungen & Erstattungen',help:'Hilfe',contact:'Kontakt',legalNotice:'Impressum',termsSale:'Allgemeine Verkaufsbedingungen',termsUse:'Nutzungsbedingungen',privacy:'Datenschutzerklärung',cookies:'Cookie-Richtlinie',consent:'Einwilligungsverwaltung'}
  };

  const shell = {
    fr:{skip:'Aller au contenu',preview:'Catalogue de démonstration · aucun paiement réel',footerPreview:'Aperçu produit. Aucun paiement réel ni réservation de stock.',search:'Rechercher',account:'Compte',bag:'Panier',language:'Langue',discover:'Découvrir',help:'Aide',delivery:'Livraisons',returns:'Retours',contact:'Contact',home:'Accueil',favourites:'Favoris',open:'Ouvrir',continue:'Continuer',back:'Retour',previewOnly:'Aperçu uniquement',empty:'Aucune donnée réelle n’est chargée dans cet aperçu.',brand:'Une marque de l’écosystème ZOS'},
    pt:{skip:'Ir para o conteúdo',preview:'Catálogo demonstrativo · sem pagamentos reais',footerPreview:'Preview de produto. Sem pagamentos reais nem reserva de stock.',search:'Pesquisar',account:'Conta',bag:'Carrinho',language:'Idioma',discover:'Descobrir',help:'Ajuda',delivery:'Entregas',returns:'Devoluções',contact:'Contacto',home:'Início',favourites:'Favoritos',open:'Abrir',continue:'Continuar',back:'Voltar',previewOnly:'Apenas Preview',empty:'Nenhum dado real é carregado neste Preview.',brand:'Uma marca do ecossistema ZOS'},
    en:{skip:'Skip to content',preview:'Demo catalogue · no live payments',footerPreview:'Product preview. No live payments or stock reservations.',search:'Search',account:'Account',bag:'Bag',language:'Language',discover:'Discover',help:'Help',delivery:'Delivery',returns:'Returns',contact:'Contact',home:'Home',favourites:'Favourites',open:'Open',continue:'Continue',back:'Back',previewOnly:'Preview only',empty:'No live data is loaded in this Preview.',brand:'A brand of the ZOS ecosystem'},
    es:{skip:'Ir al contenido',preview:'Catálogo de demostración · sin pagos reales',footerPreview:'Vista previa de producto. Sin pagos reales ni reservas de stock.',search:'Buscar',account:'Cuenta',bag:'Carrito',language:'Idioma',discover:'Descubrir',help:'Ayuda',delivery:'Entregas',returns:'Devoluciones',contact:'Contacto',home:'Inicio',favourites:'Favoritos',open:'Abrir',continue:'Continuar',back:'Volver',previewOnly:'Solo Preview',empty:'No se cargan datos reales en este Preview.',brand:'Una marca del ecosistema ZOS'},
    it:{skip:'Vai al contenuto',preview:'Catalogo dimostrativo · nessun pagamento reale',footerPreview:'Anteprima prodotto. Nessun pagamento reale né prenotazione dello stock.',search:'Cerca',account:'Account',bag:'Carrello',language:'Lingua',discover:'Scopri',help:'Aiuto',delivery:'Consegne',returns:'Resi',contact:'Contatti',home:'Home',favourites:'Preferiti',open:'Apri',continue:'Continua',back:'Indietro',previewOnly:'Solo Preview',empty:'Nessun dato reale viene caricato in questa Preview.',brand:'Un marchio dell’ecosistema ZOS'},
    de:{skip:'Zum Inhalt',preview:'Demokatalog · keine echten Zahlungen',footerPreview:'Produktvorschau. Keine echten Zahlungen oder Bestandsreservierungen.',search:'Suchen',account:'Konto',bag:'Warenkorb',language:'Sprache',discover:'Entdecken',help:'Hilfe',delivery:'Lieferung',returns:'Rücksendungen',contact:'Kontakt',home:'Start',favourites:'Favoriten',open:'Öffnen',continue:'Weiter',back:'Zurück',previewOnly:'Nur Preview',empty:'In dieser Preview werden keine Live-Daten geladen.',brand:'Eine Marke des ZOS-Ökosystems'}
  };

  const groupIntro = {
    fr:{commerce:'Découvrez la sélection Z Fashion dans une page dédiée, avec une navigation et des filtres propres à cette destination.',customer:'Retrouvez vos commandes, favoris et adresses.',checkout:'Finalisez votre commande en quelques étapes. Dans cet aperçu, aucun paiement ni aucune commande réelle n’est créé.',service:'Informations et assistance Z Fashion dans une page dédiée.',legal:'Cadre juridique et confidentialité préparés pour le lancement. Le contenu final fera l’objet d’une validation juridique avant la mise en ligne.'},
    pt:{commerce:'Descubra a seleção Z Fashion numa página própria, com navegação e filtros dedicados.',customer:'Encontre as suas encomendas, favoritos e moradas.',checkout:'Percurso de compra Z Fashion preparado em Preview. Nenhum pagamento, stock ou encomenda real é criado.',service:'Informação e apoio Z Fashion numa página dedicada.',legal:'Enquadramento jurídico e privacidade preparados para lançamento. O conteúdo final será validado juridicamente antes de Produção.'},
    en:{commerce:'Discover the Z Fashion selection on a dedicated page with navigation and filters specific to this destination.',customer:'Find your orders, favourites and addresses.',checkout:'Z Fashion checkout journey prepared in Preview mode. No real payment, stock reservation or order is created.',service:'Z Fashion information and support on a dedicated page.',legal:'Legal and privacy framework prepared for launch. Final wording remains subject to legal validation before Production.'},
    es:{commerce:'Descubre la selección Z Fashion en una página propia, con navegación y filtros específicos.',customer:'Encuentra tus pedidos, favoritos y direcciones.',checkout:'Proceso de compra Z Fashion preparado en modo Preview. No se crea ningún pago, reserva de stock ni pedido real.',service:'Información y asistencia Z Fashion en una página dedicada.',legal:'Marco legal y de privacidad preparado para el lanzamiento. El texto final deberá validarse jurídicamente antes de Producción.'},
    it:{commerce:'Scopri la selezione Z Fashion in una pagina dedicata, con navigazione e filtri specifici.',customer:'Ritrova i tuoi ordini, preferiti e indirizzi.',checkout:'Percorso checkout Z Fashion predisposto in modalità Preview. Non vengono creati pagamenti, riserve di stock o ordini reali.',service:'Informazioni e assistenza Z Fashion in una pagina dedicata.',legal:'Quadro legale e privacy predisposti per il lancio. I testi finali saranno sottoposti a validazione legale prima della Produzione.'},
    de:{commerce:'Entdecken Sie die Z Fashion Auswahl auf einer eigenen Seite mit passender Navigation und Filtern.',customer:'Ihre Bestellungen, Favoriten und Adressen auf einen Blick.',checkout:'Z Fashion Checkout im Preview-Modus. Es werden keine echten Zahlungen, Reservierungen oder Bestellungen erstellt.',service:'Z Fashion Informationen und Support auf einer eigenen Seite.',legal:'Rechtlicher und datenschutzbezogener Rahmen für den Launch vorbereitet. Die finalen Texte werden vor Produktion rechtlich geprüft.'}
  };

  const categoryIntro = {
    fr:{new:'Les dernières arrivées de nos boutiques partenaires.',women:'Vêtements, chaussures et accessoires femme, sélectionnés dans nos boutiques partenaires.',men:'Vêtements, chaussures et accessoires homme, sélectionnés dans nos boutiques partenaires.',kids:'Vêtements et chaussures enfant, confortables et faciles à porter.',sport:'Sneakers et tenues de sport pour la ville comme pour l’entraînement.',accessories:'Sacs, chaussures et petite maroquinerie de nos boutiques partenaires.',beauty:'Soins et beauté sélectionnés par nos boutiques partenaires.',sale:'Pièces à prix réduit, dans la limite des stocks des boutiques.',search:'Recherchez une marque, une pièce ou une boutique.',corners:'Nos boutiques partenaires, chacune avec sa sélection et son style.',corner:'La sélection de cette boutique partenaire.',bag:'Les pièces que vous avez choisies, regroupées par boutique.',favourites:'Les pièces que vous avez enregistrées pour plus tard.'},
    pt:{new:'As últimas novidades das nossas boutiques parceiras.',women:'Roupa, calçado e acessórios de mulher, selecionados nas nossas boutiques parceiras.',men:'Roupa, calçado e acessórios de homem, selecionados nas nossas boutiques parceiras.',kids:'Roupa e calçado de criança, confortáveis e fáceis de usar.',sport:'Sapatilhas e roupa de desporto para a cidade e para o treino.',accessories:'Malas, calçado e pequena marroquinaria das nossas boutiques parceiras.',beauty:'Cuidados e beleza selecionados pelas nossas boutiques parceiras.',sale:'Peças com preço reduzido, limitadas ao stock das boutiques.',search:'Pesquise uma marca, uma peça ou uma boutique.',corners:'As nossas boutiques parceiras, cada uma com a sua seleção e estilo.',corner:'A seleção desta boutique parceira.',bag:'As peças que escolheu, agrupadas por boutique.',favourites:'As peças que guardou para mais tarde.'},
    en:{new:'The latest arrivals from our partner boutiques.',women:'Women’s clothing, shoes and accessories, selected from our partner boutiques.',men:'Men’s clothing, shoes and accessories, selected from our partner boutiques.',kids:'Kids’ clothing and shoes, comfortable and easy to wear.',sport:'Sneakers and sportswear for the city and for training.',accessories:'Bags, shoes and small leather goods from our partner boutiques.',beauty:'Skincare and beauty selected by our partner boutiques.',sale:'Reduced-price pieces, while boutique stock lasts.',search:'Search for a brand, a piece or a boutique.',corners:'Our partner boutiques, each with its own selection and style.',corner:'This partner boutique’s selection.',bag:'The pieces you have chosen, grouped by boutique.',favourites:'The pieces you have saved for later.'},
    es:{new:'Las últimas novedades de nuestras boutiques colaboradoras.',women:'Ropa, calzado y accesorios de mujer, seleccionados en nuestras boutiques colaboradoras.',men:'Ropa, calzado y accesorios de hombre, seleccionados en nuestras boutiques colaboradoras.',kids:'Ropa y calzado infantil, cómodos y fáciles de llevar.',sport:'Zapatillas y ropa deportiva para la ciudad y el entrenamiento.',accessories:'Bolsos, calzado y pequeña marroquinería de nuestras boutiques colaboradoras.',beauty:'Cuidado y belleza seleccionados por nuestras boutiques colaboradoras.',sale:'Prendas con precio reducido, hasta agotar el stock de las boutiques.',search:'Busca una marca, una prenda o una boutique.',corners:'Nuestras boutiques colaboradoras, cada una con su selección y su estilo.',corner:'La selección de esta boutique colaboradora.',bag:'Las prendas que has elegido, agrupadas por boutique.',favourites:'Las prendas que has guardado para más tarde.'},
    it:{new:'Gli ultimi arrivi dalle nostre boutique partner.',women:'Abbigliamento, scarpe e accessori donna, selezionati nelle nostre boutique partner.',men:'Abbigliamento, scarpe e accessori uomo, selezionati nelle nostre boutique partner.',kids:'Abbigliamento e scarpe per bambini, comodi e facili da indossare.',sport:'Sneaker e abbigliamento sportivo per la città e l’allenamento.',accessories:'Borse, scarpe e piccola pelletteria dalle nostre boutique partner.',beauty:'Cura e bellezza selezionate dalle nostre boutique partner.',sale:'Capi a prezzo ridotto, fino a esaurimento dello stock delle boutique.',search:'Cerca un brand, un articolo o una boutique.',corners:'Le nostre boutique partner, ognuna con la propria selezione e il proprio stile.',corner:'La selezione di questa boutique partner.',bag:'Gli articoli che hai scelto, raggruppati per boutique.',favourites:'Gli articoli che hai salvato per dopo.'},
    de:{new:'Die neuesten Ankünfte unserer Partner-Boutiquen.',women:'Damenmode, Schuhe und Accessoires, ausgewählt aus unseren Partner-Boutiquen.',men:'Herrenmode, Schuhe und Accessoires, ausgewählt aus unseren Partner-Boutiquen.',kids:'Kinderkleidung und -schuhe, bequem und unkompliziert.',sport:'Sneaker und Sportbekleidung für Stadt und Training.',accessories:'Taschen, Schuhe und kleine Lederwaren aus unseren Partner-Boutiquen.',beauty:'Pflege und Beauty, ausgewählt von unseren Partner-Boutiquen.',sale:'Reduzierte Teile, solange der Boutique-Bestand reicht.',search:'Suchen Sie nach Marke, Artikel oder Boutique.',corners:'Unsere Partner-Boutiquen, jede mit eigener Auswahl und eigenem Stil.',corner:'Die Auswahl dieser Partner-Boutique.',bag:'Ihre ausgewählten Artikel, nach Boutique gruppiert.',favourites:'Die Artikel, die Sie für später gespeichert haben.'}
  };

  const groupEyebrow = {
    fr:{commerce:'Z Fashion',customer:'Mon espace',checkout:'Commande',service:'Aide',legal:'Informations légales'},
    pt:{commerce:'Z Fashion',customer:'A minha área',checkout:'Encomenda',service:'Ajuda',legal:'Informação legal'},
    en:{commerce:'Z Fashion',customer:'My account',checkout:'Checkout',service:'Help',legal:'Legal information'},
    es:{commerce:'Z Fashion',customer:'Mi espacio',checkout:'Pedido',service:'Ayuda',legal:'Información legal'},
    it:{commerce:'Z Fashion',customer:'La mia area',checkout:'Ordine',service:'Aiuto',legal:'Note legali'},
    de:{commerce:'Z Fashion',customer:'Mein Bereich',checkout:'Bestellung',service:'Hilfe',legal:'Rechtliches'}
  };

  window.ZFashionCustomerRoutes = {routes,titles,shell,groupIntro,categoryIntro,groupEyebrow};
})();
