(() => {
  const CATALOG = window.ZFashionCustomerCatalog;
  const STATE = window.ZFashionCustomerState;

  const copy = {
    fr:{preview:'Données de démonstration enregistrées uniquement dans ce navigateur.',emptyFav:'Votre sélection est vide.',emptyFavCopy:'Ajoutez des pièces depuis le catalogue Z Fashion.',emptyBag:'Votre panier est vide.',emptyBagCopy:'Le panier Preview peut contenir des pièces de plusieurs boutiques.',continueShopping:'Continuer mes achats',summary:'Résumé',subtotal:'Sous-total',delivery:'Livraison',free:'À définir',total:'Total Preview',checkout:'Continuer vers le checkout',bagBoundary:'Aucun paiement, réservation de stock ou commande réelle ne sera créé.',remove:'Retirer',signIn:'Se connecter',create:'Créer un compte',signInCopy:'Prévisualisation de l’accès client. L’authentification réelle n’est pas activée.',createCopy:'Prévisualisation de la création de compte Z Fashion. Aucun compte réel n’est créé.',email:'E-mail',password:'Mot de passe',firstName:'Prénom',lastName:'Nom',authDisabled:'Authentification réelle désactivée',profile:'Profil Preview',profileCopy:'Ces informations sont fictives et servent uniquement à valider l’interface.',phone:'Téléphone',language:'Langue préférée',addresses:'Adresses Preview',default:'Par défaut',orders:'Commandes Preview',placed:'Passée le',delivered:'Livrée',in_transit:'En transit',pending:'En préparation',viewOrder:'Voir la commande',packages:'Colis par boutique',tracking:'Suivi',size:'Taille',qty:'Qté',orderSummary:'Résumé de commande',returns:'Retours Preview',returnEligible:'Éligible au retour Preview',returnUnavailable:'Retour non disponible',startReturn:'Démarrer un retour Preview',returnNotice:'Cette action ne crée aucun retour réel.',trackingTitle:'Suivi Preview',trackingCopy:'La chronologie illustre le suivi multi-boutiques sans appeler de transporteur réel.',confirmed:'Commande confirmée',prepared:'Préparée par la boutique',shipped:'Expédiée',arrived:'Livrée',current:'Étape actuelle',localOnly:'État local Preview',favourites:'Favoris',bag:'Panier',ordersLabel:'Commandes',addressesLabel:'Adresses'},
    pt:{preview:'Dados demonstrativos guardados apenas neste navegador.',emptyFav:'A sua seleção está vazia.',emptyFavCopy:'Adicione peças a partir do catálogo Z Fashion.',emptyBag:'O seu carrinho está vazio.',emptyBagCopy:'O carrinho Preview pode conter peças de várias boutiques.',continueShopping:'Continuar a comprar',summary:'Resumo',subtotal:'Subtotal',delivery:'Entrega',free:'A definir',total:'Total Preview',checkout:'Continuar para checkout',bagBoundary:'Nenhum pagamento, reserva de stock ou encomenda real será criado.',remove:'Remover',signIn:'Entrar',create:'Criar conta',signInCopy:'Pré-visualização do acesso cliente. A autenticação real não está ativa.',createCopy:'Pré-visualização da criação de conta Z Fashion. Nenhuma conta real é criada.',email:'E-mail',password:'Palavra-passe',firstName:'Nome',lastName:'Apelido',authDisabled:'Autenticação real desativada',profile:'Perfil Preview',profileCopy:'Estes dados são fictícios e servem apenas para validar a interface.',phone:'Telefone',language:'Idioma preferido',addresses:'Moradas Preview',default:'Principal',orders:'Encomendas Preview',placed:'Efetuada em',delivered:'Entregue',in_transit:'Em trânsito',pending:'Em preparação',viewOrder:'Ver encomenda',packages:'Volumes por boutique',tracking:'Seguimento',size:'Tamanho',qty:'Qtd',orderSummary:'Resumo da encomenda',returns:'Devoluções Preview',returnEligible:'Elegível para devolução Preview',returnUnavailable:'Devolução indisponível',startReturn:'Iniciar devolução Preview',returnNotice:'Esta ação não cria uma devolução real.',trackingTitle:'Seguimento Preview',trackingCopy:'A cronologia ilustra o seguimento multi-boutique sem consultar uma transportadora real.',confirmed:'Encomenda confirmada',prepared:'Preparada pela boutique',shipped:'Expedida',arrived:'Entregue',current:'Etapa atual',localOnly:'Estado local Preview',favourites:'Favoritos',bag:'Carrinho',ordersLabel:'Encomendas',addressesLabel:'Moradas'},
    en:{preview:'Demonstrative data stored only in this browser.',emptyFav:'Your edit is empty.',emptyFavCopy:'Add pieces from the Z Fashion catalogue.',emptyBag:'Your bag is empty.',emptyBagCopy:'The Preview bag can hold pieces from multiple boutiques.',continueShopping:'Continue shopping',summary:'Summary',subtotal:'Subtotal',delivery:'Delivery',free:'To be defined',total:'Preview total',checkout:'Continue to checkout',bagBoundary:'No real payment, stock reservation or order will be created.',remove:'Remove',signIn:'Sign in',create:'Create account',signInCopy:'Customer access preview. Real authentication is not enabled.',createCopy:'Z Fashion account-creation preview. No real account is created.',email:'Email',password:'Password',firstName:'First name',lastName:'Last name',authDisabled:'Real authentication disabled',profile:'Preview profile',profileCopy:'These details are fictional and exist only to validate the interface.',phone:'Phone',language:'Preferred language',addresses:'Preview addresses',default:'Default',orders:'Preview orders',placed:'Placed on',delivered:'Delivered',in_transit:'In transit',pending:'Preparing',viewOrder:'View order',packages:'Packages by boutique',tracking:'Tracking',size:'Size',qty:'Qty',orderSummary:'Order summary',returns:'Preview returns',returnEligible:'Eligible for Preview return',returnUnavailable:'Return unavailable',startReturn:'Start Preview return',returnNotice:'This action creates no real return.',trackingTitle:'Preview tracking',trackingCopy:'The timeline illustrates multi-boutique tracking without contacting a real carrier.',confirmed:'Order confirmed',prepared:'Prepared by boutique',shipped:'Shipped',arrived:'Delivered',current:'Current step',localOnly:'Local Preview state',favourites:'Favourites',bag:'Bag',ordersLabel:'Orders',addressesLabel:'Addresses'},
    es:{preview:'Datos demostrativos guardados solo en este navegador.',emptyFav:'Tu selección está vacía.',emptyFavCopy:'Añade piezas desde el catálogo Z Fashion.',emptyBag:'Tu carrito está vacío.',emptyBagCopy:'El carrito Preview puede contener piezas de varias boutiques.',continueShopping:'Seguir comprando',summary:'Resumen',subtotal:'Subtotal',delivery:'Entrega',free:'Por definir',total:'Total Preview',checkout:'Continuar al checkout',bagBoundary:'No se creará ningún pago, reserva de stock ni pedido real.',remove:'Eliminar',signIn:'Acceder',create:'Crear cuenta',signInCopy:'Vista previa del acceso cliente. La autenticación real no está activa.',createCopy:'Vista previa de creación de cuenta Z Fashion. No se crea ninguna cuenta real.',email:'E-mail',password:'Contraseña',firstName:'Nombre',lastName:'Apellido',authDisabled:'Autenticación real desactivada',profile:'Perfil Preview',profileCopy:'Estos datos son ficticios y solo sirven para validar la interfaz.',phone:'Teléfono',language:'Idioma preferido',addresses:'Direcciones Preview',default:'Predeterminada',orders:'Pedidos Preview',placed:'Realizado el',delivered:'Entregado',in_transit:'En tránsito',pending:'En preparación',viewOrder:'Ver pedido',packages:'Paquetes por boutique',tracking:'Seguimiento',size:'Talla',qty:'Cant.',orderSummary:'Resumen del pedido',returns:'Devoluciones Preview',returnEligible:'Elegible para devolución Preview',returnUnavailable:'Devolución no disponible',startReturn:'Iniciar devolución Preview',returnNotice:'Esta acción no crea ninguna devolución real.',trackingTitle:'Seguimiento Preview',trackingCopy:'La cronología ilustra el seguimiento multi-boutique sin consultar un transportista real.',confirmed:'Pedido confirmado',prepared:'Preparado por la boutique',shipped:'Enviado',arrived:'Entregado',current:'Etapa actual',localOnly:'Estado local Preview',favourites:'Favoritos',bag:'Carrito',ordersLabel:'Pedidos',addressesLabel:'Direcciones'},
    it:{preview:'Dati dimostrativi salvati solo in questo browser.',emptyFav:'La tua selezione è vuota.',emptyFavCopy:'Aggiungi articoli dal catalogo Z Fashion.',emptyBag:'Il tuo carrello è vuoto.',emptyBagCopy:'Il carrello Preview può contenere articoli di più boutique.',continueShopping:'Continua lo shopping',summary:'Riepilogo',subtotal:'Subtotale',delivery:'Consegna',free:'Da definire',total:'Totale Preview',checkout:'Continua al checkout',bagBoundary:'Non verranno creati pagamenti, prenotazioni stock o ordini reali.',remove:'Rimuovi',signIn:'Accedi',create:'Crea account',signInCopy:'Anteprima accesso cliente. L’autenticazione reale non è attiva.',createCopy:'Anteprima creazione account Z Fashion. Non viene creato alcun account reale.',email:'E-mail',password:'Password',firstName:'Nome',lastName:'Cognome',authDisabled:'Autenticazione reale disattivata',profile:'Profilo Preview',profileCopy:'Questi dati sono fittizi e servono solo a validare l’interfaccia.',phone:'Telefono',language:'Lingua preferita',addresses:'Indirizzi Preview',default:'Predefinito',orders:'Ordini Preview',placed:'Effettuato il',delivered:'Consegnato',in_transit:'In transito',pending:'In preparazione',viewOrder:'Vedi ordine',packages:'Pacchi per boutique',tracking:'Tracciamento',size:'Taglia',qty:'Qtà',orderSummary:'Riepilogo ordine',returns:'Resi Preview',returnEligible:'Idoneo al reso Preview',returnUnavailable:'Reso non disponibile',startReturn:'Avvia reso Preview',returnNotice:'Questa azione non crea alcun reso reale.',trackingTitle:'Tracciamento Preview',trackingCopy:'La timeline illustra il tracking multi-boutique senza contattare un corriere reale.',confirmed:'Ordine confermato',prepared:'Preparato dalla boutique',shipped:'Spedito',arrived:'Consegnato',current:'Fase attuale',localOnly:'Stato locale Preview',favourites:'Preferiti',bag:'Carrello',ordersLabel:'Ordini',addressesLabel:'Indirizzi'},
    de:{preview:'Demodaten werden nur in diesem Browser gespeichert.',emptyFav:'Ihre Auswahl ist leer.',emptyFavCopy:'Fügen Sie Artikel aus dem Z Fashion Katalog hinzu.',emptyBag:'Ihr Warenkorb ist leer.',emptyBagCopy:'Der Preview-Warenkorb kann Artikel aus mehreren Boutiquen enthalten.',continueShopping:'Weiter einkaufen',summary:'Übersicht',subtotal:'Zwischensumme',delivery:'Lieferung',free:'Noch festzulegen',total:'Preview-Gesamt',checkout:'Weiter zum Checkout',bagBoundary:'Es werden keine echte Zahlung, Bestandsreservierung oder Bestellung erstellt.',remove:'Entfernen',signIn:'Anmelden',create:'Konto erstellen',signInCopy:'Vorschau des Kundenzugangs. Echte Authentifizierung ist nicht aktiviert.',createCopy:'Vorschau der Z Fashion Kontoerstellung. Es wird kein echtes Konto erstellt.',email:'E-Mail',password:'Passwort',firstName:'Vorname',lastName:'Nachname',authDisabled:'Echte Authentifizierung deaktiviert',profile:'Preview-Profil',profileCopy:'Diese Angaben sind fiktiv und dienen nur der UI-Validierung.',phone:'Telefon',language:'Bevorzugte Sprache',addresses:'Preview-Adressen',default:'Standard',orders:'Preview-Bestellungen',placed:'Bestellt am',delivered:'Geliefert',in_transit:'Unterwegs',pending:'In Vorbereitung',viewOrder:'Bestellung ansehen',packages:'Pakete je Boutique',tracking:'Sendungsverfolgung',size:'Größe',qty:'Anz.',orderSummary:'Bestellübersicht',returns:'Preview-Rücksendungen',returnEligible:'Für Preview-Rückgabe geeignet',returnUnavailable:'Rückgabe nicht verfügbar',startReturn:'Preview-Rückgabe starten',returnNotice:'Diese Aktion erstellt keine echte Rücksendung.',trackingTitle:'Preview-Sendungsverfolgung',trackingCopy:'Die Timeline zeigt Multi-Boutique-Tracking ohne einen echten Versanddienst aufzurufen.',confirmed:'Bestellung bestätigt',prepared:'Von Boutique vorbereitet',shipped:'Versandt',arrived:'Geliefert',current:'Aktueller Schritt',localOnly:'Lokaler Preview-Status',favourites:'Favoriten',bag:'Warenkorb',ordersLabel:'Bestellungen',addressesLabel:'Adressen'}
  };

  const c = (locale,key) => copy[locale]?.[key] || copy.fr[key] || key;
  const product = id => CATALOG.products.find(p=>p.id===id);
  const partner = id => CATALOG.partners.find(p=>p.id===id);
  const pcopy = (item,locale) => item.copy[locale] || item.copy.fr;
  const money = (value,locale) => new Intl.NumberFormat(({fr:'fr-FR',pt:'pt-PT',en:'en-GB',es:'es-ES',it:'it-IT',de:'de-DE'})[locale],{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value);
  const status = (value,locale) => c(locale,value) || value;

  const favouriteCard = (item,locale) => {
    const text = pcopy(item,locale); const store=partner(item.partnerId);
    return `<article class="commerce-product-card"><button class="favourite-toggle active" data-remove-favourite="${item.id}" aria-label="${c(locale,'remove')}">♥</button><a class="commerce-product-image" href="/produit/${item.slug}"><img src="${item.image}" alt="${text.name}"></a><div class="commerce-product-meta"><div><span class="commerce-brand">${item.brand}</span><a class="commerce-name" href="/produit/${item.slug}">${text.name}</a></div><div class="commerce-price"><strong>${money(item.price,locale)}</strong></div></div><a class="commerce-partner" href="/corner/${store.id}">${store.name} · ${store.city}</a></article>`;
  };

  const empty = (locale,title,body) => `<div class="customer-empty"><h2>${title}</h2><p>${body}</p><a class="route-button" href="/nouveautes">${c(locale,'continueShopping')}</a></div>`;

  const renderFavourites = locale => {
    const state=STATE.snapshot(); const items=state.favourites.map(product).filter(Boolean);
    if(!items.length) return empty(locale,c(locale,'emptyFav'),c(locale,'emptyFavCopy'));
    return `<div class="favourites-heading"><span>${items.length} · ${c(locale,'favourites')}</span><span>${c(locale,'localOnly')}</span></div><div class="commerce-product-grid">${items.map(item=>favouriteCard(item,locale)).join('')}</div><p class="customer-local-note">${c(locale,'preview')}</p>`;
  };

  const renderBag = locale => {
    const state=STATE.snapshot();
    if(!state.bag.length) return empty(locale,c(locale,'emptyBag'),c(locale,'emptyBagCopy'));
    let subtotal=0;
    const lines=state.bag.map(entry=>{const item=product(entry.productId);if(!item)return '';const text=pcopy(item,locale);const store=partner(item.partnerId);const line=item.price*entry.qty;subtotal+=line;return `<article class="bag-line"><img src="${item.image}" alt="${text.name}"><div><small>${store.name} · ${store.city}</small><h3><a href="/produit/${item.slug}">${text.name}</a></h3><p>${c(locale,'size')}: ${entry.size}</p><div class="bag-line-controls"><button type="button" data-bag-minus="${item.id}" data-size="${entry.size}">−</button><span>${entry.qty}</span><button type="button" data-bag-plus="${item.id}" data-size="${entry.size}">+</button><button class="bag-remove" type="button" data-bag-remove="${item.id}" data-size="${entry.size}">${c(locale,'remove')}</button></div></div><strong class="bag-line-price">${money(line,locale)}</strong></article>`}).join('');
    return `<div class="bag-layout"><div class="bag-lines">${lines}</div><aside class="bag-summary"><h2>${c(locale,'summary')}</h2><div class="bag-summary-row"><span>${c(locale,'subtotal')}</span><strong>${money(subtotal,locale)}</strong></div><div class="bag-summary-row"><span>${c(locale,'delivery')}</span><span>${c(locale,'free')}</span></div><div class="bag-summary-row total"><span>${c(locale,'total')}</span><strong>${money(subtotal,locale)}</strong></div><a class="route-button" href="/checkout">${c(locale,'checkout')}</a><p class="bag-boundary">${c(locale,'bagBoundary')}</p></aside></div><p class="customer-local-note">${c(locale,'preview')}</p>`;
  };

  const renderLogin = locale => `<div class="preview-auth"><section class="preview-auth-panel"><h2>${c(locale,'signIn')}</h2><p>${c(locale,'signInCopy')}</p><form class="preview-form"><label>${c(locale,'email')}<input type="email" value="camille.preview@example.com" disabled></label><label>${c(locale,'password')}<input type="password" value="preview" disabled></label><button class="route-button" type="button" disabled>${c(locale,'authDisabled')}</button></form><p class="preview-auth-boundary">${c(locale,'preview')}</p></section><section class="preview-auth-panel"><h2>${c(locale,'create')}</h2><p>${c(locale,'createCopy')}</p><form class="preview-form"><label>${c(locale,'firstName')}<input value="Camille" disabled></label><label>${c(locale,'lastName')}<input value="Martin" disabled></label><label>${c(locale,'email')}<input type="email" value="nouveau.preview@example.com" disabled></label><button class="route-button" type="button" disabled>${c(locale,'authDisabled')}</button></form><p class="preview-auth-boundary">${c(locale,'preview')}</p></section></div>`;

  const renderDashboard = locale => {const s=STATE.snapshot();return `<div class="account-dashboard"><article class="route-card"><span class="route-index">01</span><div><h3>${c(locale,'profile')}</h3><p>${s.profile.firstName} ${s.profile.lastName}</p></div><a href="/compte/profil">${c(locale,'profile')} →</a></article><article class="route-card"><span class="route-index">02</span><div><h3>${c(locale,'addressesLabel')}</h3><p>${s.addresses.length}</p></div><a href="/compte/adresses">${c(locale,'addresses')} →</a></article><article class="route-card"><span class="route-index">03</span><div><h3>${c(locale,'ordersLabel')}</h3><p>${s.orders.length}</p></div><a href="/compte/commandes">${c(locale,'orders')} →</a></article><article class="route-card"><span class="route-index">04</span><div><h3>${c(locale,'favourites')}</h3><p>${s.favourites.length}</p></div><a href="/favoris">${c(locale,'favourites')} →</a></article><article class="route-card"><span class="route-index">05</span><div><h3>${c(locale,'bag')}</h3><p>${s.bag.reduce((n,i)=>n+i.qty,0)}</p></div><a href="/panier">${c(locale,'bag')} →</a></article></div><p class="customer-local-note">${c(locale,'preview')}</p>`};

  const renderProfile = locale => {const p=STATE.snapshot().profile;return `<div class="profile-grid"><article class="profile-card"><h2>${c(locale,'profile')}</h2><p>${c(locale,'profileCopy')}</p><div class="profile-details"><div><span>${c(locale,'firstName')}</span><strong>${p.firstName}</strong></div><div><span>${c(locale,'lastName')}</span><strong>${p.lastName}</strong></div><div><span>${c(locale,'email')}</span><strong>${p.email}</strong></div><div><span>${c(locale,'phone')}</span><strong>${p.phone}</strong></div><div><span>${c(locale,'language')}</span><strong>${locale.toUpperCase()}</strong></div></div></article><article class="profile-card"><h2>${c(locale,'localOnly')}</h2><p>${c(locale,'preview')}</p><div class="status-strip"><div><strong>Auth</strong><span>Disabled</span></div><div><strong>Persistence</strong><span>Browser only</span></div><div><strong>ZOS</strong><span>No live write</span></div></div></article></div>`};

  const renderAddresses = locale => `<div class="address-grid">${STATE.snapshot().addresses.map(a=>`<article class="address-card"><span class="address-badge">${a.default?c(locale,'default'):a.label}</span><h2>${a.label}</h2><p>${a.line1}<br>${a.postalCode} ${a.city}<br>${a.country}</p></article>`).join('')}</div><p class="customer-local-note">${c(locale,'preview')}</p>`;

  const renderOrders = locale => `<div class="orders-list">${STATE.snapshot().orders.map(o=>`<article class="order-card"><div><div class="order-card-header"><h2>${o.id}</h2><span class="order-status">${status(o.status,locale)}</span></div><div class="order-meta"><span>${c(locale,'placed')}: ${o.placedAt}</span><span>${o.packages.length} · ${c(locale,'packages')}</span><strong>${money(o.total,locale)}</strong></div></div><a href="/compte/commandes/${o.id}">${c(locale,'viewOrder')} →</a></article>`).join('')}</div><p class="customer-local-note">${c(locale,'preview')}</p>`;

  const packageItems = (pkg,locale) => pkg.items.map(line=>{const item=product(line.productId);const text=pcopy(item,locale);return `<div class="package-item"><img src="${item.image}" alt="${text.name}"><div><strong>${text.name}</strong><small>${c(locale,'size')}: ${line.size} · ${c(locale,'qty')}: ${line.qty}</small></div><span>${money(item.price*line.qty,locale)}</span></div>`}).join('');
  const renderOrder = (route,locale) => {const id=decodeURIComponent(location.pathname.split('/').pop());const o=STATE.snapshot().orders.find(order=>order.id===id);if(!o)return empty(locale,id,c(locale,'preview'));return `<div class="order-detail"><div class="package-list">${o.packages.map(pkg=>{const store=partner(pkg.partnerId);return `<article class="package-card"><div class="package-head"><div><h3>${store.name}</h3><span>${store.city} · ${store.country}</span></div><span>${status(pkg.status,locale)}<br>${c(locale,'tracking')}: ${pkg.tracking}</span></div>${packageItems(pkg,locale)}</article>`}).join('')}</div><aside class="order-summary"><h3>${c(locale,'orderSummary')}</h3><div class="bag-summary-row"><span>${o.id}</span><span>${status(o.status,locale)}</span></div><div class="bag-summary-row"><span>${c(locale,'placed')}</span><span>${o.placedAt}</span></div><div class="bag-summary-row total"><span>${c(locale,'total')}</span><strong>${money(o.total,locale)}</strong></div><a class="route-button secondary" href="/compte/suivi">${c(locale,'tracking')}</a></aside></div><p class="customer-local-note">${c(locale,'preview')}</p>`};

  const renderReturns = locale => {const delivered=STATE.snapshot().orders.filter(o=>o.status==='delivered');return `<div class="return-grid">${delivered.flatMap(o=>o.packages.flatMap(pkg=>pkg.items.map(line=>{const item=product(line.productId);const text=pcopy(item,locale);return `<article class="return-card"><div><h2>${text.name}</h2><p>${o.id} · ${c(locale,'size')}: ${line.size}<br>${c(locale,'returnEligible')}</p></div><button class="route-button secondary" type="button" data-return-preview="${item.id}">${c(locale,'startReturn')}</button></article>`}))).join('')}</div><p class="customer-local-note">${c(locale,'returnNotice')}</p>`};

  const renderTracking = locale => {const o=STATE.snapshot().orders.find(order=>order.status==='in_transit') || STATE.snapshot().orders[0];const pkg=o.packages[0];const store=partner(pkg.partnerId);const steps=[['confirmed',true],['prepared',true],['shipped',true],['arrived',pkg.status==='delivered']];return `<article class="tracking-card"><p class="eyebrow">${o.id} · ${store.name}</p><h2>${c(locale,'trackingTitle')}</h2><p>${c(locale,'trackingCopy')}</p><div class="tracking-timeline">${steps.map(([key,done])=>`<div class="tracking-event ${done?'':'pending'}"><strong>${c(locale,key)}</strong><span>${done?c(locale,'current'):c(locale,'pending')}</span></div>`).join('')}</div><p class="customer-local-note">${c(locale,'tracking')}: ${pkg.tracking}</p></article>`};

  const render = (route,locale) => {
    if(route.type==='favourites')return renderFavourites(locale);
    if(route.type==='bag')return renderBag(locale);
    if(route.type==='login')return renderLogin(locale);
    if(route.type==='account')return renderDashboard(locale);
    if(route.id==='profile')return renderProfile(locale);
    if(route.id==='addresses')return renderAddresses(locale);
    if(route.type==='orders')return renderOrders(locale);
    if(route.type==='order')return renderOrder(route,locale);
    if(route.id==='returns')return renderReturns(locale);
    if(route.type==='tracking')return renderTracking(locale);
    return `<div class="customer-empty"><h2>${route.id}</h2><p>${c(locale,'preview')}</p></div>`;
  };

  const wire = (route,locale,rerender) => {
    document.querySelectorAll('[data-remove-favourite]').forEach(btn=>btn.addEventListener('click',()=>{STATE.toggleFavourite(btn.dataset.removeFavourite);rerender()}));
    document.querySelectorAll('[data-bag-minus]').forEach(btn=>btn.addEventListener('click',()=>{const s=STATE.snapshot();const item=s.bag.find(i=>i.productId===btn.dataset.bagMinus&&i.size===btn.dataset.size);if(item)STATE.setBagQty(item.productId,item.size,item.qty-1);rerender()}));
    document.querySelectorAll('[data-bag-plus]').forEach(btn=>btn.addEventListener('click',()=>{const s=STATE.snapshot();const item=s.bag.find(i=>i.productId===btn.dataset.bagPlus&&i.size===btn.dataset.size);if(item)STATE.setBagQty(item.productId,item.size,item.qty+1);rerender()}));
    document.querySelectorAll('[data-bag-remove]').forEach(btn=>btn.addEventListener('click',()=>{STATE.removeBag(btn.dataset.bagRemove,btn.dataset.size);rerender()}));
    document.querySelectorAll('[data-return-preview]').forEach(btn=>btn.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('zfashion:toast',{detail:c(locale,'returnNotice')}))));
  };

  window.ZFashionCustomerArea={render,wire,copy};
  window.Z_FASHION_CUSTOMER_AREA='PREVIEW_PASS';
})();
