(() => {
  const supported=['fr','pt','en','es','it','de'];
  const defaultLocale='fr';

  const copy={
    fr:{preview:'Catalogue de démonstration · aucun paiement réel',search:'Rechercher',account:'Compte',allSale:'Toute la sélection',women:'Femme',men:'Homme',children:'Enfant',sports:'Sport',accessories:'Accessoires',beauty:'Beauté',sale:'Soldes',newSeason:'Nouvelle saison · 2026',heroTitle:'Découvrir le style.<br>Acheter mieux.',heroCopy:'Boutiques, marques et collections dans une expérience unique — avec sélection éditoriale, stock partenaire et finalisation de commande Z Fashion.',shopNow:'Découvrir la sélection',exploreCorners:'Explorer les Corners',multiBoutique:'Multi-boutiques',multiBoutiqueCopy:'Un panier, plusieurs boutiques',freshStock:'Stock actualisé',freshStockCopy:'Disponibilité par boutique',easyReturns:'Retours simplifiés',easyReturnsCopy:'Conditions claires par commande',zosIdentity:'Compte unique',zosIdentityCopy:'Préférences et favoris réunis',editWomen:'Éditorial',womenEditTitle:'Luxe discret, nouveau rythme',editMen:'Homme',menEditTitle:'Coupe structurée sans effort',editNew:'Nouveautés',newEditTitle:'Les pièces qui définissent la saison',discover:'Découvrir',allSaleTitle:'Toute la sélection',allSaleCopy:'Une sélection transversale de plusieurs boutiques. Dans cet aperçu, les produits sont démonstratifs.',all:'Tout',partnerBoutiques:'Boutiques partenaires',cornersTitle:'Corners',cornersCopy:'Chaque partenaire conserve son identité, sa sélection et son stock dans l’expérience Z Fashion.',viewAll:'Voir tout',enterCorner:'Entrer dans le Corner',privateSale:'Vente privée',campaignTitle:'Une sélection réservée aux membres.',campaignCopy:'Aperçu des campagnes Z Fashion : l’accès, le stock et les conditions commerciales restent définis par boutique et par marché.',memberAccess:'Accès membre',support:'Aide',delivery:'Livraisons',returns:'Retours',contact:'Contact',footerPreview:'Aperçu produit. Aucun paiement réel ni réservation de stock.',cart:'Panier',checkoutPreview:'Paiement indisponible dans cet aperçu',close:'Fermer',sortBy:'Trier',featured:'Sélection',priceAsc:'Prix ↑',priceDesc:'Prix ↓',partnerFulfilment:'Lors de la commande réelle, les expéditions et les retours seront identifiés par boutique.',accountTitle:'Votre compte vous accompagne également dans Z Fashion.',accountCopy:'Favoris, boutiques suivies, adresses et préférences restent liés au même compte, selon les autorisations de chaque produit.',savedStyle:'Enregistrer styles et favoris',followCorners:'Suivre les Corners et les boutiques',sharedAddresses:'Réutiliser les adresses autorisées',signinPreview:'Connexion disponible après activation',accountBoundary:'Aperçu : aucune session réelle n’est ouverte.',home:'Accueil',popularSearches:'Recherches populaires'},
    pt:{preview:'Catálogo demonstrativo · sem pagamentos reais',search:'Pesquisar',account:'Conta',allSale:'Toda a seleção',women:'Mulher',men:'Homem',children:'Criança',sports:'Desporto',accessories:'Acessórios',beauty:'Beleza',sale:'Saldos',newSeason:'Nova estação · 2026',heroTitle:'Descobrir estilo.<br>Comprar melhor.',heroCopy:'Boutiques, marcas e coleções numa experiência única — com curadoria editorial, stock do parceiro e finalização de compra Z Fashion.',shopNow:'Descobrir a seleção',exploreCorners:'Explorar Corners',multiBoutique:'Multi-boutique',multiBoutiqueCopy:'Um carrinho, várias boutiques',freshStock:'Stock atualizado',freshStockCopy:'Disponibilidade por boutique',easyReturns:'Devoluções simples',easyReturnsCopy:'Condições claras por encomenda',zosIdentity:'Conta única',zosIdentityCopy:'Preferências e favoritos reunidos',editWomen:'Editorial',womenEditTitle:'Luxo discreto, novo ritmo',editMen:'Homem',menEditTitle:'Alfaiataria sem esforço',editNew:'Novidades',newEditTitle:'Peças que definem a estação',discover:'Descobrir',allSaleTitle:'Toda a seleção',allSaleCopy:'Uma seleção transversal de várias boutiques. Neste preview, os produtos são demonstrativos.',all:'Tudo',partnerBoutiques:'Boutiques parceiras',cornersTitle:'Corners',cornersCopy:'Cada parceiro mantém identidade, curadoria e stock próprios dentro da experiência Z Fashion.',viewAll:'Ver tudo',enterCorner:'Entrar no Corner',privateSale:'Venda privada',campaignTitle:'Uma seleção reservada a membros.',campaignCopy:'Preview das campanhas Z Fashion: o acesso, o stock e as condições comerciais continuam definidos por boutique e mercado.',memberAccess:'Acesso de membro',support:'Apoio',delivery:'Entregas',returns:'Devoluções',contact:'Contacto',footerPreview:'Preview de produto. Sem pagamentos reais nem reserva de stock.',cart:'Carrinho',checkoutPreview:'Pagamento indisponível neste preview',close:'Fechar',sortBy:'Ordenar',featured:'Destaques',priceAsc:'Preço ↑',priceDesc:'Preço ↓',partnerFulfilment:'Na compra real, os envios e as devoluções serão identificados por boutique.',accountTitle:'A sua conta acompanha-o também na Z Fashion.',accountCopy:'Favoritos, boutiques seguidas, moradas e preferências permanecem ligados à mesma conta, segundo as autorizações de cada produto.',savedStyle:'Guardar estilo e favoritos',followCorners:'Seguir Corners e boutiques',sharedAddresses:'Reutilizar moradas autorizadas',signinPreview:'Login disponível após ativação',accountBoundary:'Preview: nenhuma sessão real é iniciada.',home:'Início',popularSearches:'Pesquisas populares'},
    en:{preview:'Demo catalogue · no live payments',search:'Search',account:'Account',allSale:'Shop all',women:'Women',men:'Men',children:'Kids',sports:'Sport',accessories:'Accessories',beauty:'Beauty',sale:'Sale',newSeason:'New season · 2026',heroTitle:'Discover style.<br>Shop better.',heroCopy:'Boutiques, brands and collections in one experience — with editorial curation, partner stock and Z Fashion checkout.',shopNow:'Discover the edit',exploreCorners:'Explore Corners',multiBoutique:'Multi-boutique',multiBoutiqueCopy:'One bag, multiple boutiques',freshStock:'Updated stock',freshStockCopy:'Availability by boutique',easyReturns:'Simple returns',easyReturnsCopy:'Clear conditions by order',zosIdentity:'One account',zosIdentityCopy:'Preferences and favourites together',editWomen:'Editorial',womenEditTitle:'Quiet luxury, new rhythm',editMen:'Men',menEditTitle:'Effortless tailoring',editNew:'New in',newEditTitle:'Pieces that define the season',discover:'Discover',allSaleTitle:'Shop all',allSaleCopy:'A cross-boutique selection. Products in this preview are demonstrative.',all:'All',partnerBoutiques:'Partner boutiques',cornersTitle:'Corners',cornersCopy:'Each partner keeps its own identity, curation and stock within the Z Fashion experience.',viewAll:'View all',enterCorner:'Enter Corner',privateSale:'Private sale',campaignTitle:'A selection reserved for members.',campaignCopy:'Preview of Z Fashion campaigns: access, stock and commercial terms remain defined by boutique and market.',memberAccess:'Member access',support:'Support',delivery:'Delivery',returns:'Returns',contact:'Contact',footerPreview:'Product preview. No live payments or stock reservations.',cart:'Bag',checkoutPreview:'Checkout unavailable in this preview',close:'Close',sortBy:'Sort',featured:'Featured',priceAsc:'Price ↑',priceDesc:'Price ↓',partnerFulfilment:'In live checkout, shipping and returns will be identified by boutique.',accountTitle:'Your account follows you into Z Fashion.',accountCopy:'Favourites, followed boutiques, addresses and preferences stay connected to the same account, within each product’s permissions.',savedStyle:'Save styles and favourites',followCorners:'Follow Corners and boutiques',sharedAddresses:'Reuse authorised addresses',signinPreview:'Sign-in available after activation',accountBoundary:'Preview: no real session is started.',home:'Home',popularSearches:'Popular searches'},
    es:{preview:'Catálogo de demostración · sin pagos reales',search:'Buscar',account:'Cuenta',allSale:'Toda la selección',women:'Mujer',men:'Hombre',children:'Niños',sports:'Deporte',accessories:'Accesorios',beauty:'Belleza',sale:'Rebajas',newSeason:'Nueva temporada · 2026',heroTitle:'Descubrir estilo.<br>Comprar mejor.',heroCopy:'Boutiques, marcas y colecciones en una sola experiencia — con selección editorial, stock de la boutique y checkout Z Fashion.',shopNow:'Descubrir la selección',exploreCorners:'Explorar Corners',multiBoutique:'Multi-boutique',multiBoutiqueCopy:'Un carrito, varias boutiques',freshStock:'Stock actualizado',freshStockCopy:'Disponibilidad por boutique',easyReturns:'Devoluciones sencillas',easyReturnsCopy:'Condiciones claras por pedido',zosIdentity:'Una cuenta',zosIdentityCopy:'Preferencias y favoritos reunidos',editWomen:'Editorial',womenEditTitle:'Lujo discreto, nuevo ritmo',editMen:'Hombre',menEditTitle:'Sastrería sin esfuerzo',editNew:'Novedades',newEditTitle:'Piezas que definen la temporada',discover:'Descubrir',allSaleTitle:'Toda la selección',allSaleCopy:'Una selección transversal de varias boutiques. Los productos de esta vista previa son demostrativos.',all:'Todo',partnerBoutiques:'Boutiques colaboradoras',cornersTitle:'Corners',cornersCopy:'Cada boutique conserva su identidad, selección y stock dentro de la experiencia Z Fashion.',viewAll:'Ver todo',enterCorner:'Entrar en el Corner',privateSale:'Venta privada',campaignTitle:'Una selección reservada a miembros.',campaignCopy:'Vista previa de las campañas Z Fashion: el acceso, el stock y las condiciones comerciales siguen definidos por boutique y mercado.',memberAccess:'Acceso de miembro',support:'Ayuda',delivery:'Envíos',returns:'Devoluciones',contact:'Contacto',footerPreview:'Vista previa de producto. Sin pagos reales ni reservas de stock.',cart:'Carrito',checkoutPreview:'Pago no disponible en esta vista previa',close:'Cerrar',sortBy:'Ordenar',featured:'Destacados',priceAsc:'Precio ↑',priceDesc:'Precio ↓',partnerFulfilment:'En el checkout real, envíos y devoluciones se identificarán por boutique.',accountTitle:'Tu cuenta te acompaña también en Z Fashion.',accountCopy:'Favoritos, boutiques seguidas, direcciones y preferencias permanecen vinculados a la misma cuenta, según los permisos de cada producto.',savedStyle:'Guardar estilo y favoritos',followCorners:'Seguir Corners y boutiques',sharedAddresses:'Reutilizar direcciones autorizadas',signinPreview:'Inicio de sesión disponible tras la activación',accountBoundary:'Vista previa: no se inicia ninguna sesión real.',home:'Inicio',popularSearches:'Búsquedas populares'},
    it:{preview:'Catalogo dimostrativo · nessun pagamento reale',search:'Cerca',account:'Account',allSale:'Tutta la selezione',women:'Donna',men:'Uomo',children:'Bambini',sports:'Sport',accessories:'Accessori',beauty:'Bellezza',sale:'Saldi',newSeason:'Nuova stagione · 2026',heroTitle:'Scoprire lo stile.<br>Acquistare meglio.',heroCopy:'Boutique, brand e collezioni in un’unica esperienza — con curatela editoriale, stock della boutique e checkout Z Fashion.',shopNow:'Scopri la selezione',exploreCorners:'Esplora i Corners',multiBoutique:'Multi-boutique',multiBoutiqueCopy:'Un carrello, più boutique',freshStock:'Stock aggiornato',freshStockCopy:'Disponibilità per boutique',easyReturns:'Resi semplici',easyReturnsCopy:'Condizioni chiare per ordine',zosIdentity:'Un solo account',zosIdentityCopy:'Preferenze e preferiti riuniti',editWomen:'Editoriale',womenEditTitle:'Lusso discreto, nuovo ritmo',editMen:'Uomo',menEditTitle:'Sartoria senza sforzo',editNew:'Novità',newEditTitle:'I capi che definiscono la stagione',discover:'Scopri',allSaleTitle:'Tutta la selezione',allSaleCopy:'Una selezione trasversale di più boutique. I prodotti di questa anteprima sono dimostrativi.',all:'Tutto',partnerBoutiques:'Boutique partner',cornersTitle:'Corners',cornersCopy:'Ogni boutique mantiene identità, selezione e stock propri all’interno dell’esperienza Z Fashion.',viewAll:'Vedi tutto',enterCorner:'Entra nel Corner',privateSale:'Vendita privata',campaignTitle:'Una selezione riservata ai membri.',campaignCopy:'Anteprima delle campagne Z Fashion: accesso, stock e condizioni commerciali restano definiti per boutique e mercato.',memberAccess:'Accesso membro',support:'Assistenza',delivery:'Consegne',returns:'Resi',contact:'Contatti',footerPreview:'Anteprima prodotto. Nessun pagamento reale né prenotazione dello stock.',cart:'Carrello',checkoutPreview:'Pagamento non disponibile in questa anteprima',close:'Chiudi',sortBy:'Ordina',featured:'In evidenza',priceAsc:'Prezzo ↑',priceDesc:'Prezzo ↓',partnerFulfilment:'Nel checkout reale, spedizioni e resi saranno identificati per boutique.',accountTitle:'Il tuo account ti accompagna anche in Z Fashion.',accountCopy:'Preferiti, boutique seguite, indirizzi e preferenze restano collegati allo stesso account, secondo le autorizzazioni di ciascun prodotto.',savedStyle:'Salva stile e preferiti',followCorners:'Segui Corners e boutique',sharedAddresses:'Riutilizza indirizzi autorizzati',signinPreview:'Accesso disponibile dopo l’attivazione',accountBoundary:'Anteprima: nessuna sessione reale viene avviata.',home:'Home',popularSearches:'Ricerche popolari'},
    de:{preview:'Demokatalog · keine echten Zahlungen',search:'Suchen',account:'Konto',allSale:'Gesamte Auswahl',women:'Damen',men:'Herren',children:'Kinder',sports:'Sport',accessories:'Accessoires',beauty:'Beauty',sale:'Sale',newSeason:'Neue Saison · 2026',heroTitle:'Stil entdecken.<br>Besser einkaufen.',heroCopy:'Boutiquen, Marken und Kollektionen in einem Erlebnis — mit redaktioneller Auswahl, Boutique-Bestand und Z Fashion Checkout.',shopNow:'Auswahl entdecken',exploreCorners:'Corners entdecken',multiBoutique:'Multi-Boutique',multiBoutiqueCopy:'Ein Warenkorb, mehrere Boutiquen',freshStock:'Aktueller Bestand',freshStockCopy:'Verfügbarkeit je Boutique',easyReturns:'Einfache Rückgabe',easyReturnsCopy:'Klare Bedingungen je Bestellung',zosIdentity:'Ein Konto',zosIdentityCopy:'Präferenzen und Favoriten gebündelt',editWomen:'Editorial',womenEditTitle:'Leiser Luxus, neuer Rhythmus',editMen:'Herren',menEditTitle:'Müheloses Tailoring',editNew:'Neuheiten',newEditTitle:'Pieces, die die Saison prägen',discover:'Entdecken',allSaleTitle:'Gesamte Auswahl',allSaleCopy:'Eine Boutique-übergreifende Auswahl. Die Produkte in dieser Vorschau sind demonstrativ.',all:'Alle',partnerBoutiques:'Partner-Boutiquen',cornersTitle:'Corners',cornersCopy:'Jede Boutique behält ihre eigene Identität, Auswahl und ihren Bestand innerhalb von Z Fashion.',viewAll:'Alle ansehen',enterCorner:'Corner öffnen',privateSale:'Private Sale',campaignTitle:'Eine Auswahl exklusiv für Mitglieder.',campaignCopy:'Vorschau der Z Fashion Kampagnen: Zugang, Bestand und Konditionen bleiben je Boutique und Markt definiert.',memberAccess:'Mitgliederzugang',support:'Service',delivery:'Lieferung',returns:'Rückgabe',contact:'Kontakt',footerPreview:'Produktvorschau. Keine echten Zahlungen oder Bestandsreservierungen.',cart:'Warenkorb',checkoutPreview:'Checkout in dieser Vorschau nicht verfügbar',close:'Schließen',sortBy:'Sortieren',featured:'Empfohlen',priceAsc:'Preis ↑',priceDesc:'Preis ↓',partnerFulfilment:'Im Live-Checkout werden Versand und Rückgabe je Boutique ausgewiesen.',accountTitle:'Ihr Konto begleitet Sie auch in Z Fashion.',accountCopy:'Favoriten, gefolgte Boutiquen, Adressen und Präferenzen bleiben mit demselben Konto verbunden, entsprechend den Berechtigungen des jeweiligen Produkts.',savedStyle:'Stil und Favoriten speichern',followCorners:'Corners und Boutiquen folgen',sharedAddresses:'Autorisierte Adressen wiederverwenden',signinPreview:'Anmeldung nach Aktivierung verfügbar',accountBoundary:'Vorschau: Es wird keine echte Sitzung gestartet.',home:'Start',popularSearches:'Beliebte Suchen'}
  };

  const productsByLocale={
    fr:{p1:['Blazer structuré en laine','Blazer à la construction épurée, épaule souple et laine froide. Une pièce de transition pensée pour le quotidien.'],p2:['Manteau minimaliste en laine','Manteau aux lignes longues et à la finition minimaliste, sélectionné par Maison Nord.'],p3:['Surchemise technique','Surchemise légère à construction technique et volume décontracté, idéale pour les superpositions.'],p4:['Sac Arc en cuir','Sac compact en cuir à structure courbe, finitions discrètes et bandoulière réglable.'],p5:['Runner 02','Sneaker de course urbaine au profil léger, semelle réactive et construction respirante.'],p6:['Robe colonne','Robe longue à encolure épurée et tissu fluide au toucher sec.'],p7:['Bomber en daim','Bomber en daim souple à finition mate et proportions contemporaines.'],p8:['Mocassin 19','Mocassin de construction classique réinterprété avec semelle fine et bout allongé.']},
    pt:{p1:['Blazer estruturado em lã','Blazer de construção limpa, ombro suave e lã fria. Uma peça de transição pensada para o quotidiano.'],p2:['Casaco minimalista em lã','Casaco de linhas longas e acabamento minimalista, selecionado pela Maison Nord.'],p3:['Overshirt técnica','Overshirt leve com construção técnica e volume descontraído para sobreposição.'],p4:['Mala Arc em pele','Mala compacta em pele com estrutura curva, ferragens discretas e alça ajustável.'],p5:['Runner 02','Sapatilha de corrida urbana com perfil leve, sola responsiva e construção respirável.'],p6:['Vestido coluna','Vestido de silhueta longa com decote depurado e tecido fluido de toque seco.'],p7:['Bomber em camurça','Bomber em camurça macia com acabamento mate e proporções contemporâneas.'],p8:['Loafer 19','Loafer de construção clássica reinterpretado com sola fina e biqueira alongada.']},
    en:{p1:['Structured wool blazer','Cleanly constructed blazer with a soft shoulder and cool wool. A transitional piece designed for everyday wear.'],p2:['Minimal wool coat','Long-line wool coat with a minimal finish, selected by Maison Nord.'],p3:['Technical overshirt','Lightweight technical overshirt with a relaxed volume designed for layering.'],p4:['Arc leather bag','Compact leather bag with a curved structure, discreet hardware and adjustable strap.'],p5:['Runner 02','Lightweight urban running sneaker with a responsive sole and breathable construction.'],p6:['Column dress','Long column dress with a clean neckline and fluid, dry-touch fabric.'],p7:['Suede bomber','Soft suede bomber with a matte finish and contemporary proportions.'],p8:['Loafer 19','Classic loafer construction reinterpreted with a slim sole and elongated toe.']},
    es:{p1:['Blazer estructurado de lana','Blazer de construcción limpia, hombro suave y lana fría. Una prenda de transición pensada para el día a día.'],p2:['Abrigo minimalista de lana','Abrigo de líneas largas y acabado minimalista, seleccionado por Maison Nord.'],p3:['Sobrecamisa técnica','Sobrecamisa ligera de construcción técnica y volumen relajado, ideal para superponer.'],p4:['Bolso Arc de piel','Bolso compacto de piel con estructura curva, herrajes discretos y correa ajustable.'],p5:['Runner 02','Zapatilla urbana de running con perfil ligero, suela reactiva y construcción transpirable.'],p6:['Vestido columna','Vestido largo de línea columna, escote depurado y tejido fluido de tacto seco.'],p7:['Bomber de ante','Bomber de ante suave con acabado mate y proporciones contemporáneas.'],p8:['Mocasín 19','Mocasín clásico reinterpretado con suela fina y puntera alargada.']},
    it:{p1:['Blazer strutturato in lana','Blazer dalla costruzione pulita, spalla morbida e lana fresca. Un capo di transizione pensato per ogni giorno.'],p2:['Cappotto minimal in lana','Cappotto dalle linee lunghe e dalla finitura minimalista, selezionato da Maison Nord.'],p3:['Overshirt tecnica','Overshirt leggera dalla costruzione tecnica e volume rilassato, ideale per il layering.'],p4:['Borsa Arc in pelle','Borsa compatta in pelle con struttura curva, dettagli discreti e tracolla regolabile.'],p5:['Runner 02','Sneaker da running urbano dal profilo leggero, suola reattiva e costruzione traspirante.'],p6:['Abito a colonna','Abito lungo dalla linea a colonna, scollo pulito e tessuto fluido dal tocco asciutto.'],p7:['Bomber in camoscio','Bomber in morbido camoscio con finitura opaca e proporzioni contemporanee.'],p8:['Mocassino 19','Mocassino classico reinterpretato con suola sottile e punta allungata.']},
    de:{p1:['Strukturierter Wollblazer','Klar konstruierter Blazer mit weicher Schulter und kühler Wolle. Ein Übergangsteil für den Alltag.'],p2:['Minimalistischer Wollmantel','Lang geschnittener Wollmantel mit minimalistischer Verarbeitung, ausgewählt von Maison Nord.'],p3:['Technisches Overshirt','Leichtes technisches Overshirt mit entspanntem Volumen, ideal für Layering.'],p4:['Arc Ledertasche','Kompakte Ledertasche mit geschwungener Form, dezenten Beschlägen und verstellbarem Riemen.'],p5:['Runner 02','Leichter Urban-Running-Sneaker mit reaktiver Sohle und atmungsaktiver Konstruktion.'],p6:['Säulenkleid','Langes Kleid mit klarer Säulenlinie, reduziertem Ausschnitt und fließendem Stoff mit trockenem Griff.'],p7:['Bomberjacke aus Wildleder','Weiche Wildleder-Bomberjacke mit mattem Finish und zeitgemäßen Proportionen.'],p8:['Loafer 19','Klassischer Loafer, neu interpretiert mit schlanker Sohle und verlängerter Spitze.']}
  };

  const badgeCopy={
    fr:{New:'Nouveau',Private:'Privé',Icon:'Icône',Fresh:'Nouveauté',Limited:'Édition limitée'},pt:{New:'Novo',Private:'Privado',Icon:'Ícone',Fresh:'Novidade',Limited:'Limitado'},en:{New:'New',Private:'Private',Icon:'Icon',Fresh:'Fresh',Limited:'Limited'},es:{New:'Nuevo',Private:'Privado',Icon:'Icono',Fresh:'Novedad',Limited:'Limitado'},it:{New:'Nuovo',Private:'Privato',Icon:'Icona',Fresh:'Novità',Limited:'Limitato'},de:{New:'Neu',Private:'Privat',Icon:'Ikone',Fresh:'Neuheit',Limited:'Limitiert'}
  };

  const staticCopy={
    fr:{previewLabel:'APERÇU',language:'Langue',wishlist:'Favoris',bag:'Panier',footerAll:'Toute la sélection',endorsement:'Une marque de l’écosystème ZOS',skip:'Aller au contenu',searchPlaceholder:'Rechercher marques, pièces, boutiques…',count:'pièces',size:'Taille',sizeGuide:'Guide des tailles',demoStock:'Stock de démonstration — aucune réservation',returnRule:'Retours définis par boutique',add:'Ajouter au panier',remove:'Retirer',emptyCart:'Votre panier est vide.',emptyCartCopy:'Ajoutez des pièces de différentes boutiques.',emptyWish:'Votre sélection est vide.',emptyWishCopy:'Enregistrez les pièces que vous souhaitez retrouver.',bagSearch:'Sac',corner:['Mode femme contemporaine','Essentiels contemporains','Cuir & accessoires'],locations:['PORTO · PORTUGAL','PARIS · FRANCE','MILAN · ITALIE'],title:'Z Fashion — Aperçu',description:'Z Fashion — aperçu du storefront mode multi-boutiques.'},
    pt:{previewLabel:'PREVIEW',language:'Idioma',wishlist:'Favoritos',bag:'Carrinho',footerAll:'Toda a seleção',endorsement:'Uma marca do ecossistema ZOS',skip:'Saltar para o conteúdo',searchPlaceholder:'Pesquisar marcas, peças, boutiques…',count:'peças',size:'Tamanho',sizeGuide:'Guia de tamanhos',demoStock:'Stock demonstrativo — sem reserva',returnRule:'Devoluções definidas por boutique',add:'Adicionar ao carrinho',remove:'Remover',emptyCart:'O seu carrinho está vazio.',emptyCartCopy:'Adicione peças de diferentes boutiques.',emptyWish:'A sua seleção está vazia.',emptyWishCopy:'Guarde as peças a que quer voltar.',bagSearch:'Mala',corner:['Moda feminina contemporânea','Essenciais contemporâneos','Pele e acessórios'],locations:['PORTO · PORTUGAL','PARIS · FRANÇA','MILÃO · ITÁLIA'],title:'Z Fashion — Preview',description:'Z Fashion — preview do marketplace de moda multi-boutique.'},
    en:{previewLabel:'PREVIEW',language:'Language',wishlist:'Favourites',bag:'Bag',footerAll:'Shop all',endorsement:'A brand of the ZOS ecosystem',skip:'Skip to content',searchPlaceholder:'Search brands, pieces, boutiques…',count:'pieces',size:'Size',sizeGuide:'Size guide',demoStock:'Demo stock — no reservation',returnRule:'Returns defined by boutique',add:'Add to bag',remove:'Remove',emptyCart:'Your bag is empty.',emptyCartCopy:'Add pieces from different boutiques.',emptyWish:'Your edit is empty.',emptyWishCopy:'Save pieces you want to revisit.',bagSearch:'Bag',corner:['Contemporary womenswear','Modern essentials','Leather & accessories'],locations:['PORTO · PORTUGAL','PARIS · FRANCE','MILAN · ITALY'],title:'Z Fashion — Preview',description:'Z Fashion — multi-boutique fashion storefront preview.'},
    es:{previewLabel:'VISTA PREVIA',language:'Idioma',wishlist:'Favoritos',bag:'Carrito',footerAll:'Toda la selección',endorsement:'Una marca del ecosistema ZOS',skip:'Ir al contenido',searchPlaceholder:'Buscar marcas, prendas, boutiques…',count:'piezas',size:'Talla',sizeGuide:'Guía de tallas',demoStock:'Stock de demostración — sin reserva',returnRule:'Devoluciones definidas por boutique',add:'Añadir al carrito',remove:'Eliminar',emptyCart:'Tu carrito está vacío.',emptyCartCopy:'Añade piezas de diferentes boutiques.',emptyWish:'Tu selección está vacía.',emptyWishCopy:'Guarda las piezas que quieras volver a ver.',bagSearch:'Bolso',corner:['Moda femenina contemporánea','Esenciales contemporáneos','Piel y accesorios'],locations:['OPORTO · PORTUGAL','PARÍS · FRANCIA','MILÁN · ITALIA'],title:'Z Fashion — Vista previa',description:'Z Fashion — vista previa del storefront de moda multi-boutique.'},
    it:{previewLabel:'ANTEPRIMA',language:'Lingua',wishlist:'Preferiti',bag:'Carrello',footerAll:'Tutta la selezione',endorsement:'Un marchio dell’ecosistema ZOS',skip:'Vai al contenuto',searchPlaceholder:'Cerca brand, capi, boutique…',count:'capi',size:'Taglia',sizeGuide:'Guida alle taglie',demoStock:'Stock dimostrativo — nessuna prenotazione',returnRule:'Resi definiti per boutique',add:'Aggiungi al carrello',remove:'Rimuovi',emptyCart:'Il tuo carrello è vuoto.',emptyCartCopy:'Aggiungi capi da boutique diverse.',emptyWish:'La tua selezione è vuota.',emptyWishCopy:'Salva i capi che vuoi ritrovare.',bagSearch:'Borsa',corner:['Moda donna contemporanea','Essenziali contemporanei','Pelle e accessori'],locations:['PORTO · PORTOGALLO','PARIGI · FRANCIA','MILANO · ITALIA'],title:'Z Fashion — Anteprima',description:'Z Fashion — anteprima dello storefront moda multi-boutique.'},
    de:{previewLabel:'VORSCHAU',language:'Sprache',wishlist:'Favoriten',bag:'Warenkorb',footerAll:'Gesamte Auswahl',endorsement:'Eine Marke des ZOS-Ökosystems',skip:'Zum Inhalt springen',searchPlaceholder:'Marken, Pieces und Boutiquen suchen…',count:'Pieces',size:'Größe',sizeGuide:'Größenberatung',demoStock:'Demobestand — keine Reservierung',returnRule:'Rückgabe je Boutique geregelt',add:'In den Warenkorb',remove:'Entfernen',emptyCart:'Ihr Warenkorb ist leer.',emptyCartCopy:'Fügen Sie Pieces aus verschiedenen Boutiquen hinzu.',emptyWish:'Ihre Auswahl ist leer.',emptyWishCopy:'Speichern Sie Pieces, die Sie wiederfinden möchten.',bagSearch:'Tasche',corner:['Zeitgenössische Damenmode','Moderne Essentials','Leder & Accessoires'],locations:['PORTO · PORTUGAL','PARIS · FRANKREICH','MAILAND · ITALIEN'],title:'Z Fashion — Vorschau',description:'Z Fashion — Vorschau des Multi-Boutique-Fashion-Storefronts.'}
  };

  const baseBadge={};
  products.forEach(p=>{baseBadge[p.id]=p.badge;});

  const applyProductLocale=code=>{
    products.forEach(p=>{
      const tr=productsByLocale[code]?.[p.id]||productsByLocale.fr[p.id];
      p.name=tr[0]; p.description=tr[1]; p.badge=badgeCopy[code]?.[baseBadge[p.id]]||baseBadge[p.id];
    });
  };

  const applyStatic=code=>{
    const c=copy[code], s=staticCopy[code];
    document.querySelectorAll('[data-i18n]').forEach(el=>{const value=c[el.dataset.i18n];if(value!==undefined)el.innerHTML=value;});
    document.querySelector('.preview-label')?.replaceChildren(document.createTextNode(s.previewLabel));
    const langLabel=document.querySelector('[data-language-label]'); if(langLabel)langLabel.textContent=s.language;
    const select=document.getElementById('localeSelect'); if(select){select.value=code;select.setAttribute('aria-label',s.language);}
    const bag=document.querySelector('[data-bag-label]'); if(bag)bag.textContent=s.bag;
    const wish=document.querySelector('[data-wishlist-heading]'); if(wish)wish.textContent=s.wishlist;
    const mw=document.querySelector('[data-mobile-wishlist]'); if(mw)mw.textContent=s.wishlist;
    const footerAll=document.querySelector('[data-footer-all]'); if(footerAll)footerAll.textContent=s.footerAll;
    const endorsement=document.querySelector('[data-brand-endorsement]'); if(endorsement)endorsement.textContent=s.endorsement;
    const skip=document.querySelector('.skip-link'); if(skip)skip.textContent=s.skip;
    const searchInput=document.getElementById('searchInput'); if(searchInput)searchInput.placeholder=s.searchPlaceholder;
    const searchSr=document.querySelector('[data-search-sr]'); if(searchSr)searchSr.textContent=c.search;
    const count=document.getElementById('productCount'); if(count)count.textContent=`${document.querySelectorAll('#productGrid .product-card').length} ${s.count}`;
    document.querySelectorAll('[data-corner-copy]').forEach((el,i)=>el.textContent=s.corner[i]||el.textContent);
    document.querySelectorAll('[data-corner-location]').forEach((el,i)=>el.textContent=s.locations[i]||el.textContent);
    const bagSearch=document.querySelector('[data-search-key="bag"]'); if(bagSearch){bagSearch.textContent=s.bagSearch;bagSearch.dataset.search=s.bagSearch.toLowerCase();}
    document.title=s.title;
    const meta=document.querySelector('meta[name="description"]'); if(meta)meta.setAttribute('content',s.description);
    document.documentElement.lang=code==='fr'?'fr-FR':code==='pt'?'pt-PT':code==='en'?'en':code==='es'?'es':code==='it'?'it':code==='de'?'de-DE':code;
    document.documentElement.dataset.locale=code;
  };

  const baseToast=toast;
  toast=function(message){
    const code=supported.includes(locale)?locale:defaultLocale;
    const map={
      'Adicionado ao carrinho':{fr:'Ajouté au panier',pt:'Adicionado ao carrinho',en:'Added to bag',es:'Añadido al carrito',it:'Aggiunto al carrello',de:'Zum Warenkorb hinzugefügt'},
      'Adicionado à Wishlist':{fr:'Ajouté aux favoris',pt:'Adicionado aos favoritos',en:'Added to favourites',es:'Añadido a favoritos',it:'Aggiunto ai preferiti',de:'Zu Favoriten hinzugefügt'},
      'Removido da Wishlist':{fr:'Retiré des favoris',pt:'Removido dos favoritos',en:'Removed from favourites',es:'Eliminado de favoritos',it:'Rimosso dai preferiti',de:'Aus Favoriten entfernt'},
      'Venda Privada · Preview':{fr:'Vente privée · aperçu',pt:'Venda privada · preview',en:'Private sale · preview',es:'Venta privada · vista previa',it:'Vendita privata · anteprima',de:'Private Sale · Vorschau'}
    };
    baseToast(map[message]?.[code]||message);
  };

  const baseRenderCart=renderCart;
  renderCart=function(){
    baseRenderCart();
    const code=supported.includes(locale)?locale:defaultLocale, s=staticCopy[code];
    if(!cart.length){
      const box=document.getElementById('cartItems');
      if(box){box.innerHTML=`<div class="empty-polish"><strong>${s.emptyCart}</strong><span>${s.emptyCartCopy}</span><br><button class="button dark" data-launch-shop>${copy[code].shopNow}</button></div>`;box.querySelector('[data-launch-shop]')?.addEventListener('click',()=>{closeDrawers();setFilter('all');});}
    }
    document.querySelectorAll('#cartItems [data-remove]').forEach(btn=>btn.setAttribute('aria-label',s.remove));
    const count=document.getElementById('productCount'); if(count)count.textContent=`${document.querySelectorAll('#productGrid .product-card').length} ${s.count}`;
  };

  const baseRenderWishlist=renderWishlist;
  renderWishlist=function(){
    baseRenderWishlist();
    const code=supported.includes(locale)?locale:defaultLocale, s=staticCopy[code];
    if(!wishlist.size){
      const box=document.getElementById('wishlistItems');
      if(box){box.innerHTML=`<div class="empty-polish"><strong>${s.emptyWish}</strong><span>${s.emptyWishCopy}</span><br><button class="button dark" data-launch-wish-shop>${copy[code].shopNow}</button></div>`;box.querySelector('[data-launch-wish-shop]')?.addEventListener('click',()=>{closeDrawers();setFilter('all');});}
    }
  };

  const baseOpenProduct=openProduct;
  openProduct=function(id){
    baseOpenProduct(id);
    const code=supported.includes(locale)?locale:defaultLocale, s=staticCopy[code];
    const detail=document.querySelector('.product-detail-copy'); if(!detail)return;
    const sizeEyebrow=[...detail.querySelectorAll('.eyebrow')].find(el=>el.textContent.trim().toUpperCase()==='SIZE'); if(sizeEyebrow)sizeEyebrow.textContent=s.size.toUpperCase();
    const helper=detail.querySelector('.size-helper'); if(helper){const span=helper.querySelector('span');const btn=helper.querySelector('button');if(span)span.textContent=s.size;if(btn){btn.textContent=s.sizeGuide;btn.onclick=()=>toast(`${s.sizeGuide} · ${staticCopy[code].previewLabel.toLowerCase()}`);}}
    const service=detail.querySelector('.detail-polish'); if(service){const spans=service.querySelectorAll('span');if(spans[0])spans[0].textContent=s.demoStock;if(spans[1])spans[1].textContent=s.returnRule;}
    const add=detail.querySelector('[data-add]'); if(add)add.textContent=s.add;
    const p=products.find(x=>x.id===id), note=detail.querySelector('.partner-note');
    if(note&&p){
      const notes={fr:`Stock de démonstration · ${p.corner}. Le stock réel appartient à la boutique et sera vérifié lors de la finalisation de commande.`,pt:`Stock demonstrativo · ${p.corner}. O stock real pertence à boutique e será validado na finalização da compra.`,en:`Demo stock · ${p.corner}. Live stock belongs to the boutique and will be verified at checkout.`,es:`Stock de demostración · ${p.corner}. El stock real pertenece a la boutique y se verificará al finalizar la compra.`,it:`Stock dimostrativo · ${p.corner}. Lo stock reale appartiene alla boutique e sarà verificato al checkout.`,de:`Demobestand · ${p.corner}. Der reale Bestand gehört zur Boutique und wird beim Checkout geprüft.`};
      note.textContent=notes[code];
    }
  };

  const baseApplyLocale=applyLocale;
  applyLocale=function(next){
    const code=supported.includes(next)?next:defaultLocale;
    Object.assign(translations[code],copy[code]);
    applyProductLocale(code);
    baseApplyLocale(code);
    applyStatic(code);
    renderProducts(); renderCart(); renderWishlist();
    localStorage.setItem('zfashion_locale',code);
  };

  document.getElementById('localeSelect')?.addEventListener('change',e=>{
    const code=supported.includes(e.target.value)?e.target.value:defaultLocale;
    setTimeout(()=>{applyProductLocale(code);applyStatic(code);renderProducts();renderCart();renderWishlist();},0);
  });

  const saved=(()=>{try{return localStorage.getItem('zfashion_locale')}catch(_){return null}})();
  applyLocale(supported.includes(saved)?saved:defaultLocale);
  window.Z_FASHION_DEFAULT_LOCALE=defaultLocale;
  window.Z_FASHION_SUPPORTED_LOCALES=[...supported];
  window.Z_FASHION_MARKET_INDEPENDENT_LANGUAGE=true;
  window.Z_FASHION_MULTILINGUAL_LAUNCH='PASS';
})();
