(() => {
  const supported=['fr','pt','en','es','it','de'];
  let locale='fr';
  try { const stored=localStorage.getItem('zfashion_locale'); locale=supported.includes(stored)?stored:'fr'; } catch (_) {}

  const COPY={
    fr:{brand:'Une marque de l’écosystème ZOS',preview:'Aperçu technique · Z Fashion',home:'Retour à Z Fashion',help:'Centre d’aide',retry:'Réessayer',notFound:{code:'404',eyebrow:'PAGE INTROUVABLE',title:'Cette page n’est plus ici.',body:'L’adresse demandée ne correspond à aucune destination Z Fashion. Vous pouvez revenir à la sélection ou utiliser la recherche.',status:['Navigation','Disponible','Aucune donnée perdue']},error:{code:'503',eyebrow:'INDISPONIBILITÉ',title:'Z Fashion est momentanément indisponible.',body:'Cette page représente l’état prévu lorsqu’un service nécessaire ne peut pas répondre. Aucune commande ne doit être créée dans cet état.',status:['Service','Indisponible','Réessai sécurisé']},maintenance:{code:'Z',eyebrow:'MAINTENANCE',title:'Nous préparons la prochaine expérience.',body:'Z Fashion peut être placé temporairement en maintenance pendant une intervention planifiée. La boutique revient dès que les contrôles sont terminés.',status:['Maintenance','Planifiée','Aucun paiement actif']}},
    pt:{brand:'Uma marca do ecossistema ZOS',preview:'Preview técnico · Z Fashion',home:'Voltar ao Z Fashion',help:'Centro de ajuda',retry:'Tentar novamente',notFound:{code:'404',eyebrow:'PÁGINA NÃO ENCONTRADA',title:'Esta página já não está aqui.',body:'O endereço pedido não corresponde a nenhum destino Z Fashion. Pode regressar à seleção ou utilizar a pesquisa.',status:['Navegação','Disponível','Nenhum dado perdido']},error:{code:'503',eyebrow:'INDISPONIBILIDADE',title:'O Z Fashion está temporariamente indisponível.',body:'Este estado é apresentado quando um serviço necessário não responde. Nenhuma encomenda deve ser criada neste estado.',status:['Serviço','Indisponível','Nova tentativa segura']},maintenance:{code:'Z',eyebrow:'MANUTENÇÃO',title:'Estamos a preparar a próxima experiência.',body:'O Z Fashion pode entrar temporariamente em manutenção durante uma intervenção planeada. A boutique regressa quando os controlos terminarem.',status:['Manutenção','Planeada','Nenhum pagamento ativo']}},
    en:{brand:'A brand of the ZOS ecosystem',preview:'Technical Preview · Z Fashion',home:'Back to Z Fashion',help:'Help centre',retry:'Try again',notFound:{code:'404',eyebrow:'PAGE NOT FOUND',title:'This page is no longer here.',body:'The requested address does not match a Z Fashion destination. Return to the selection or use search.',status:['Navigation','Available','No data lost']},error:{code:'503',eyebrow:'UNAVAILABLE',title:'Z Fashion is temporarily unavailable.',body:'This is the intended state when a required service cannot respond. No order should be created while this state is shown.',status:['Service','Unavailable','Safe retry']},maintenance:{code:'Z',eyebrow:'MAINTENANCE',title:'We are preparing the next experience.',body:'Z Fashion may temporarily enter maintenance during planned work. The boutique returns once checks are complete.',status:['Maintenance','Planned','No active payment']}},
    es:{brand:'Una marca del ecosistema ZOS',preview:'Preview técnico · Z Fashion',home:'Volver a Z Fashion',help:'Centro de ayuda',retry:'Reintentar',notFound:{code:'404',eyebrow:'PÁGINA NO ENCONTRADA',title:'Esta página ya no está aquí.',body:'La dirección solicitada no corresponde a un destino Z Fashion. Vuelve a la selección o utiliza la búsqueda.',status:['Navegación','Disponible','Sin pérdida de datos']},error:{code:'503',eyebrow:'NO DISPONIBLE',title:'Z Fashion no está disponible temporalmente.',body:'Este es el estado previsto cuando un servicio necesario no responde. No se debe crear ningún pedido en este estado.',status:['Servicio','No disponible','Reintento seguro']},maintenance:{code:'Z',eyebrow:'MANTENIMIENTO',title:'Estamos preparando la próxima experiencia.',body:'Z Fashion puede entrar temporalmente en mantenimiento durante una intervención planificada. La boutique vuelve tras completar los controles.',status:['Mantenimiento','Planificado','Sin pagos activos']}},
    it:{brand:'Un marchio dell’ecosistema ZOS',preview:'Preview tecnico · Z Fashion',home:'Torna a Z Fashion',help:'Centro assistenza',retry:'Riprova',notFound:{code:'404',eyebrow:'PAGINA NON TROVATA',title:'Questa pagina non è più qui.',body:'L’indirizzo richiesto non corrisponde a una destinazione Z Fashion. Torna alla selezione o usa la ricerca.',status:['Navigazione','Disponibile','Nessun dato perso']},error:{code:'503',eyebrow:'NON DISPONIBILE',title:'Z Fashion è temporaneamente non disponibile.',body:'Questo è lo stato previsto quando un servizio necessario non risponde. Nessun ordine deve essere creato in questo stato.',status:['Servizio','Non disponibile','Nuovo tentativo sicuro']},maintenance:{code:'Z',eyebrow:'MANUTENZIONE',title:'Stiamo preparando la prossima esperienza.',body:'Z Fashion può entrare temporaneamente in manutenzione durante un intervento pianificato. La boutique torna dopo i controlli.',status:['Manutenzione','Pianificata','Nessun pagamento attivo']}},
    de:{brand:'Eine Marke des ZOS-Ökosystems',preview:'Technische Preview · Z Fashion',home:'Zurück zu Z Fashion',help:'Hilfe-Center',retry:'Erneut versuchen',notFound:{code:'404',eyebrow:'SEITE NICHT GEFUNDEN',title:'Diese Seite ist nicht mehr hier.',body:'Die angeforderte Adresse gehört zu keinem Z Fashion Ziel. Kehren Sie zur Auswahl zurück oder nutzen Sie die Suche.',status:['Navigation','Verfügbar','Keine Daten verloren']},error:{code:'503',eyebrow:'NICHT VERFÜGBAR',title:'Z Fashion ist vorübergehend nicht verfügbar.',body:'Dieser Zustand ist vorgesehen, wenn ein benötigter Dienst nicht antwortet. In diesem Zustand darf keine Bestellung erstellt werden.',status:['Service','Nicht verfügbar','Sicherer Neuversuch']},maintenance:{code:'Z',eyebrow:'WARTUNG',title:'Wir bereiten das nächste Erlebnis vor.',body:'Z Fashion kann während geplanter Arbeiten vorübergehend in Wartung gehen. Die Boutique kehrt nach Abschluss der Kontrollen zurück.',status:['Wartung','Geplant','Keine aktive Zahlung']}}
  };

  const body=document.body;
  const state=body.dataset.technicalState || (location.pathname.includes('maintenance')?'maintenance':location.pathname.includes('erreur')||location.pathname.includes('error')?'error':'notFound');
  const select=document.getElementById('technicalLocale');
  const render=()=>{
    const c=COPY[locale]||COPY.fr, s=c[state];
    document.documentElement.lang=locale==='fr'?'fr-FR':locale;
    document.documentElement.dataset.locale=locale;
    if(select) select.value=locale;
    document.getElementById('technicalPreview').textContent=c.preview;
    document.getElementById('technicalCode').textContent=s.code;
    document.getElementById('technicalEyebrow').textContent=s.eyebrow;
    document.getElementById('technicalTitle').textContent=s.title;
    document.getElementById('technicalBody').textContent=s.body;
    document.getElementById('technicalHome').textContent=c.home;
    document.getElementById('technicalHelp').textContent=state==='error'?c.retry:c.help;
    document.getElementById('technicalHelp').href=state==='error'?location.pathname:'/aide';
    document.getElementById('technicalStatus').innerHTML=s.status.map((value,i)=>`<div><strong>${['01','02','03'][i]}</strong><span>${value}</span></div>`).join('');
    document.getElementById('technicalEndorsement').textContent=c.brand;
    document.title=`Z Fashion — ${s.eyebrow}`;
  };
  select?.addEventListener('change',e=>{locale=e.target.value;try{localStorage.setItem('zfashion_locale',locale)}catch(_){}render()});
  render();
  window.Z_FASHION_TECHNICAL_STATES='PREVIEW_PASS';
})();
