// Gerado por scripts/build-fichas-data.js — nao editar a mao.
// Indice n = fichaIdx do dashboard; cada morada = campos da ficha PDF.
module.exports = [
  ...require('./shard-0.js'),
  ...require('./shard-1.js'),
  ...require('./shard-2.js'),
  ...require('./shard-3.js'),
  ...require('./shard-4.js'),
  ...require('./shard-5.js'),
  ...require('./shard-6.js'),
  ...require('./shard-7.js'),
  ...require('./shard-8.js'),
  ...require('./shard-9.js'),
  ...require('./shard-10.js'),
  ...require('./shard-11.js'),
  ...require('./shard-12.js'),
  ...require('./shard-13.js'),
  ...require('./shard-14.js'),
  ...require('./shard-15.js'),
  ...require('./shard-16.js'),
  ...require('./shard-17.js'),
  ...require('./shard-18.js'),
  ...require('./shard-19.js'),
  ...require('./shard-20.js'),
  ...require('./shard-21.js'),
  ...require('./shard-22.js'),
  ...require('./shard-23.js'),
  ...require('./shard-24.js'),
  ...require('./shard-25.js'),
  ...require('./shard-26.js'),
  ...require('./shard-27.js'),
];
