// Z Studio — unified subscription UI v1.
// Provider choice is platform-only. Trial eligibility is always server-side.
(function installZStudioBilling(global) {
  'use strict';
  const PLAN_CODES = ['weekly', 'monthly', 'annual'];
  const PLAN_SET = new Set(PLAN_CODES);
  let overlay = null;
  let statusEl = null;
  let priceEls = new Map();
  let busy = false;
  const STRINGS = Object.freeze({
    pt: { plans:'Planos', title:'Z Studio', sub:'Escolha o seu plano. O teste gratuito de 3 dias é aplicado apenas se for elegível.', weekly:'Semanal', monthly:'Mensal', annual:'Anual', subscribe:'Subscrever', restore:'Restaurar compras', manage:'Gerir subscrição', close:'Fechar', working:'A processar…', restored:'Compras restauradas.', done:'Subscrição atualizada.', unavailable:'Subscrições temporariamente indisponíveis.', auth:'Inicie sessão para gerir a subscrição.', trial:'3 dias grátis se elegível' },
    en: { plans:'Plans', title:'Z Studio', sub:'Choose your plan. The 3-day free trial is applied only when eligible.', weekly:'Weekly', monthly:'Monthly', annual:'Annual', subscribe:'Subscribe', restore:'Restore purchases', manage:'Manage subscription', close:'Close', working:'Processing…', restored:'Purchases restored.', done:'Subscription updated.', unavailable:'Subscriptions are temporarily unavailable.', auth:'Sign in to manage your subscription.', trial:'3 days free if eligible' },
    fr: { plans:'Forfaits', title:'Z Studio', sub:'Choisissez votre forfait. L’essai gratuit de 3 jours est appliqué uniquement si vous êtes éligible.', weekly:'Hebdomadaire', monthly:'Mensuel', annual:'Annuel', subscribe:'S’abonner', restore:'Restaurer les achats', manage:'Gérer l’abonnement', close:'Fermer', working:'Traitement…', restored:'Achats restaurés.', done:'Abonnement mis à jour.', unavailable:'Les abonnements sont temporairement indisponibles.', auth:'Connectez-vous pour gérer votre abonnement.', trial:'3 jours gratuits si éligible' },
    es: { plans:'Planes', title:'Z Studio', sub:'Elige tu plan. La prueba gratuita de 3 días solo se aplica si eres elegible.', weekly:'Semanal', monthly:'Mensual', annual:'Anual', subscribe:'Suscribirse', restore:'Restaurar compras', manage:'Gestionar suscripción', close:'Cerrar', working:'Procesando…', restored:'Compras restauradas.', done:'Suscripción actualizada.', unavailable:'Las suscripciones no están disponibles temporalmente.', auth:'Inicia sesión para gestionar tu suscripción.', trial:'3 días gratis si eres elegible' },
    de: { plans:'Tarife', title:'Z Studio', sub:'Wähle deinen Tarif. Die 3-tägige kostenlose Testphase gilt nur bei Berechtigung.', weekly:'Wöchentlich', monthly:'Monatlich', annual:'Jährlich', subscribe:'Abonnieren', restore:'Käufe wiederherstellen', manage:'Abo verwalten', close:'Schließen', working:'Wird verarbeitet…', restored:'Käufe wiederhergestellt.', done:'Abo aktualisiert.', unavailable:'Abonnements sind vorübergehend nicht verfügbar.', auth:'Melde dich an, um dein Abo zu verwalten.', trial:'3 Tage gratis bei Berechtigung' },
    it: { plans:'Piani', title:'Z Studio', sub:'Scegli il tuo piano. La prova gratuita di 3 giorni si applica solo se idoneo.', weekly:'Settimanale', monthly:'Mensile', annual:'Annuale', subscribe:'Abbonati', restore:'Ripristina acquisti', manage:'Gestisci abbonamento', close:'Chiudi', working:'Elaborazione…', restored:'Acquisti ripristinati.', done:'Abbonamento aggiornato.', unavailable:'Gli abbonamenti non sono temporaneamente disponibili.', auth:'Accedi per gestire il tuo abbonamento.', trial:'3 giorni gratis se idoneo' },
  });
  function lang() { const value = String((typeof state === 'object' && state?.lang) || document.documentElement.lang || 'pt').toLowerCase().slice(0,2); return STRINGS[value] ? value : 'en'; }
  function t(key) { return STRINGS[lang()][key] || STRINGS.en[key] || key; }
  function config() { return global.ZStudioCommercialConfig || null; }
  function baseUrl() { return String(config()?.baseUrl || global.ZSTUDIO_COMMERCIAL_BASE_URL || '').replace(/\/+$/, ''); }
  function enabled() { return config()?.enabled === true && /^https:\/\//.test(baseUrl()); }
  function platform() { if (global.Capacitor?.isNativePlatform?.() === true) return global.Capacitor?.getPlatform?.() || 'native'; return 'web'; }
  function targetPrice(planCode) { const minor = Number(config()?.plans?.[planCode]?.priceMinor); const currency = String(config()?.currency || 'EUR'); if (!Number.isInteger(minor) || minor <= 0) return ''; try { return new Intl.NumberFormat(lang(), {style:'currency',currency}).format(minor / 100); } catch { return `${(minor/100).toFixed(2)} ${currency}`; } }
  function setStatus(message, isError=false) { if (!statusEl) return; statusEl.textContent = message || ''; statusEl.style.color = isError ? '#D98980' : 'var(--text2, #B0B4B8)'; }
  function create(tag, props={}) { const el = document.createElement(tag); Object.entries(props).forEach(([key,value]) => { if (key === 'text') el.textContent = value; else if (key === 'className') el.className = value; else el.setAttribute(key, value); }); return el; }
  function injectStyle() { if (document.getElementById('zstudioBillingStyle')) return; const style = create('style',{id:'zstudioBillingStyle'}); style.textContent = `.zsb-trigger{margin-left:8px;padding:7px 12px;border:1px solid var(--border,#454A4F);background:transparent;color:var(--text,#F2F2EF);font:500 .74rem 'DM Sans',sans-serif;letter-spacing:.06em;border-radius:3px;cursor:pointer}.zsb-overlay{position:fixed;inset:0;z-index:1400;background:rgba(5,6,7,.86);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:20px}.zsb-card{width:min(820px,100%);max-height:min(760px,92vh);overflow:auto;background:var(--surface,#111315);border:1px solid var(--border,#454A4F);border-radius:8px;padding:24px;box-shadow:0 32px 90px rgba(0,0,0,.6)}.zsb-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.zsb-title{font:500 1.75rem 'Cormorant Garamond',serif}.zsb-sub{margin:6px 0 20px;color:var(--text2,#B0B4B8);font-size:.78rem;line-height:1.55;max-width:620px}.zsb-close{border:0;background:transparent;color:var(--text2,#B0B4B8);font-size:1.3rem;cursor:pointer}.zsb-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.zsb-plan{border:1px solid var(--border,#454A4F);border-radius:6px;padding:18px;background:var(--surface-2,#181A1D)}.zsb-plan-name{font-size:.78rem;text-transform:uppercase;letter-spacing:.14em;color:var(--text2,#B0B4B8)}.zsb-price{font:500 1.65rem 'Cormorant Garamond',serif;margin:8px 0}.zsb-trial{min-height:32px;color:var(--text2,#B0B4B8);font-size:.7rem;line-height:1.4}.zsb-buy{width:100%;margin-top:14px;padding:10px;border:1px solid var(--text,#F2F2EF);background:var(--text,#F2F2EF);color:#0A0A0A;border-radius:3px;cursor:pointer;font:500 .75rem 'DM Sans',sans-serif}.zsb-buy:disabled{opacity:.5;cursor:not-allowed}.zsb-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.zsb-action{padding:8px 12px;border:1px solid var(--border,#454A4F);background:transparent;color:var(--text,#F2F2EF);border-radius:3px;cursor:pointer;font-size:.72rem}.zsb-status{min-height:1.3em;margin-top:14px;font-size:.72rem}@media(max-width:720px){.zsb-plans{grid-template-columns:1fr}.zsb-card{padding:18px}.zsb-trigger{padding:7px 9px}}`; document.head.appendChild(style); }
  async function accessToken() { const token = await global.ZStudioAuth?.getAccessToken?.({interactive:true}); if (!token) throw Object.assign(new Error('AUTH_REQUIRED'),{code:'AUTH_REQUIRED'}); return token; }
  async function webPost(path, data) { const token = await accessToken(); let response; try { response = await fetch(baseUrl()+path,{method:'POST',headers:{Authorization:'Bearer '+token,Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(data)}); } catch (cause) { throw Object.assign(new Error('WEB_COMMERCIAL_UNAVAILABLE'),{code:'WEB_COMMERCIAL_UNAVAILABLE',cause}); } const payload = await response.json().catch(()=>null); if (!response.ok) throw Object.assign(new Error(payload?.code || 'WEB_COMMERCIAL_FAILED'),{code:payload?.code || 'WEB_COMMERCIAL_FAILED',httpStatus:response.status}); return payload; }
  async function waitFor(name, maxMs=2500) { const start = Date.now(); while (Date.now() - start < maxMs) { if (global[name]) return global[name]; await new Promise((resolve)=>setTimeout(resolve,100)); } return global[name] || null; }
  function checkoutUrl(value) { const raw = String(value || ''); let url; try { url = new URL(raw); } catch { throw new Error('WEB_CHECKOUT_URL_INVALID'); } if (url.protocol !== 'https:' || url.hostname !== 'checkout.stripe.com') throw new Error('WEB_CHECKOUT_URL_INVALID'); return url.href; }
  async function startPlan(planCode) { if (!PLAN_SET.has(planCode)) throw new Error('PLAN_INVALID'); if (busy) return; busy = true; setStatus(t('working')); document.querySelectorAll('.zsb-buy').forEach((b)=>{b.disabled=true;}); try { const p = platform(); if (p === 'ios') { const bridge = await waitFor('ZStudioApple'); if (!bridge?.isAvailable?.()) throw new Error('APPLE_NATIVE_UNAVAILABLE'); await bridge.startPurchase(planCode); setStatus(t('done')); } else if (p === 'android') { const bridge = await waitFor('ZStudioGooglePlay'); if (!bridge?.isAvailable?.()) throw new Error('GOOGLE_PLAY_NATIVE_UNAVAILABLE'); await bridge.startPurchase(planCode); setStatus(t('done')); } else { const result = await webPost('/api/web/checkout',{plan_code:planCode}); global.location.assign(checkoutUrl(result?.checkout_url)); } } catch (cause) { setStatus(cause?.code === 'AUTH_REQUIRED' ? t('auth') : t('unavailable'), true); throw cause; } finally { busy = false; document.querySelectorAll('.zsb-buy').forEach((b)=>{b.disabled=false;}); } }
  async function restore() { if (busy) return; busy=true; setStatus(t('working')); try { const p=platform(); if (p==='ios') { const bridge=await waitFor('ZStudioApple'); if (!bridge?.isAvailable?.()) throw new Error('APPLE_NATIVE_UNAVAILABLE'); await bridge.restoreCurrentPurchases({sync:true,interactive:true}); } else if (p==='android') { const bridge=await waitFor('ZStudioGooglePlay'); if (!bridge?.isAvailable?.()) throw new Error('GOOGLE_PLAY_NATIVE_UNAVAILABLE'); await accessToken(); await bridge.restoreCurrentPurchases(); } else return; setStatus(t('restored')); } catch (cause) { setStatus(cause?.code==='AUTH_REQUIRED'?t('auth'):t('unavailable'),true); throw cause; } finally { busy=false; } }
  async function manage() { if (busy) return; busy=true; setStatus(t('working')); try { if (platform()!=='web') return; const result=await webPost('/api/web/portal',{}); const raw=String(result?.portal_url||''); const url=new URL(raw); if (url.protocol!=='https:' || !/(^|\.)stripe\.com$/.test(url.hostname)) throw new Error('WEB_PORTAL_URL_INVALID'); global.location.assign(url.href); } catch (cause) { setStatus(cause?.code==='AUTH_REQUIRED'?t('auth'):t('unavailable'),true); throw cause; } finally { busy=false; } }
  async function refreshNativePrices() { try { const p=platform(); if (p==='ios') { const bridge=await waitFor('ZStudioApple',800); if (!bridge?.isAvailable?.()) return; const products=await bridge.loadProducts(); const map=new Map((products?.products||[]).map((x)=>[x.productId,x.displayPrice])); for (const plan of PLAN_CODES) { const id=config()?.plans?.[plan]?.appleProductId; if (map.get(id) && priceEls.get(plan)) priceEls.get(plan).textContent=map.get(id); } } else if (p==='android') { const bridge=await waitFor('ZStudioGooglePlay',800); if (!bridge?.isAvailable?.()) return; const result=await bridge.loadProducts(); const offers=result?.products?.[0]?.offers||[]; for (const plan of PLAN_CODES) { const offer=offers.find((x)=>x.basePlanId===plan && x.offerId==null) || offers.find((x)=>x.basePlanId===plan); const phases=offer?.pricingPhases||[]; const paid=[...phases].reverse().find((x)=>Number(x.priceAmountMicros)>0) || phases[phases.length-1]; if (paid?.formattedPrice && priceEls.get(plan)) priceEls.get(plan).textContent=paid.formattedPrice; } } } catch {} }
  function open() { if (!enabled()) return false; if (overlay) { overlay.hidden=false; refreshNativePrices(); return true; } injectStyle(); priceEls=new Map(); overlay=create('div',{className:'zsb-overlay'}); const card=create('div',{className:'zsb-card'}); const head=create('div',{className:'zsb-head'}); const titleWrap=create('div'); titleWrap.append(create('div',{className:'zsb-title',text:t('title')}),create('div',{className:'zsb-sub',text:t('sub')})); const close=create('button',{className:'zsb-close','aria-label':t('close'),text:'×'}); close.type='button'; close.addEventListener('click',()=>{overlay.hidden=true;}); head.append(titleWrap,close); card.appendChild(head); const grid=create('div',{className:'zsb-plans'}); for (const plan of PLAN_CODES) { const box=create('div',{className:'zsb-plan'}); const name=create('div',{className:'zsb-plan-name',text:t(plan)}); const price=create('div',{className:'zsb-price',text:targetPrice(plan)}); priceEls.set(plan,price); const trial=create('div',{className:'zsb-trial',text:t('trial')}); const button=create('button',{className:'zsb-buy',text:t('subscribe')}); button.type='button'; button.dataset.plan=plan; button.addEventListener('click',()=>{startPlan(plan).catch(()=>{});}); box.append(name,price,trial,button); grid.appendChild(box); } card.appendChild(grid); const actions=create('div',{className:'zsb-actions'}); if (platform()==='ios' || platform()==='android') { const restoreBtn=create('button',{className:'zsb-action',text:t('restore')}); restoreBtn.type='button'; restoreBtn.addEventListener('click',()=>{restore().catch(()=>{});}); actions.appendChild(restoreBtn); } if (platform()==='web') { const manageBtn=create('button',{className:'zsb-action',text:t('manage')}); manageBtn.type='button'; manageBtn.addEventListener('click',()=>{manage().catch(()=>{});}); actions.appendChild(manageBtn); } card.appendChild(actions); statusEl=create('div',{className:'zsb-status'}); card.appendChild(statusEl); overlay.appendChild(card); overlay.addEventListener('click',(e)=>{if(e.target===overlay) overlay.hidden=true;}); document.body.appendChild(overlay); refreshNativePrices(); return true; }
  function mount() { if (!enabled() || document.querySelector('[data-zstudio-billing-trigger]')) return false; injectStyle(); const button=create('button',{className:'zsb-trigger','data-zstudio-billing-trigger':'v1',text:t('plans')}); button.type='button'; button.addEventListener('click',open); const header=document.querySelector('header'); if (header) header.appendChild(button); else { button.style.position='fixed'; button.style.right='16px'; button.style.bottom='16px'; button.style.zIndex='1300'; document.body.appendChild(button); } return true; }
  global.ZStudioBilling=Object.freeze({enabled,platform,open,mount,startPlan,restore,manage});
  if (document.readyState==='loading') document.addEventListener('DOMContentLoaded',mount,{once:true}); else mount();
})(window);
