/* ============================================================
   Z FIND — PHASE 4 SIX-LANGUAGE UI COMPLETION
   ES · DE · IT public interface translations.
   Loaded after i18n.js and before viewmodels/app.
   ============================================================ */

(function () {
  'use strict';

  if (typeof I18N === 'undefined') {
    throw new Error('Z Find Phase 4 translations require base I18N.');
  }

  Object.assign(I18N, {
    es: {
      common: { search:'Buscar', viewAll:'Ver todo', save:'Guardar', signIn:'Iniciar sesión', publish:'Publicar su cartera', close:'Cerrar', backToResults:'← Volver a los resultados' },
      navigation: { home:'Inicio', search:'Buscar', property:'Inmueble', development:'Promoción', land:'Terrenos y Desarrollo', partner:'Socio', simulator:'Simuladores' },
      simulator: {
        title:'Simulador de Costes de Adquisición', subtitle:'Estime el impuesto de transmisiones (IMT) y el impuesto de timbre al comprar una vivienda en Portugal.',
        country:'País', propertyValue:'Valor del inmueble (€)', isHPP:'Esta será mi residencia habitual', isResident:'Soy residente fiscal en Portugal',
        calculate:'Calcular', imt:'Impuesto de transmisiones (IMT)', stampDuty:'Impuesto de timbre', total:'Total',
        tabCosts:'Costes de Adquisición', tabYield:'Rentabilidad',
      },
      yieldSim: {
        title:'Simulador de Rentabilidad', subtitle:'Introduzca sus propios supuestos — esta herramienta realiza los cálculos; nunca estima una rentabilidad por usted.',
        modeAL:'Corta estancia (Alojamento Local)', modeALD:'Alquiler de larga duración',
        propertyValue:'Valor del inmueble (€)', renovation:'Costes de reforma (€)',
        acquisitionCosts:'Costes de adquisición — IMT + Impuesto de timbre (€)', acquisitionCostsNote:'Obtenga este importe en el', acquisitionCostsLink:'Simulador de Costes de Adquisición →',
        dailyRate:'Tarifa diaria (€)', occupancy:'Ocupación (%)', platformFee:'Comisión de plataforma (%)', managementFee:'Comisión de gestión (%)', utilitiesMonthly:'Suministros — mensual (€)',
        monthlyRent:'Alquiler mensual (€)', voidMonths:'Meses vacíos / año',
        condoMonthly:'Comunidad — mensual (€)', irsRate:'Tipo de IRS sobre alquileres (%)', irsRateNote:'El tipo general es del 28 % — confirme con un asesor fiscal el tipo aplicable a su situación; los contratos de larga duración pueden beneficiarse de una reducción.',
        hasLoan:'Financiado con préstamo', loanAmount:'Importe del préstamo (€)', loanRate:'Tipo del préstamo (%)', loanYears:'Plazo del préstamo (años)',
        calculate:'Calcular', grossYield:'Rentabilidad bruta', netYield:'Rentabilidad neta', cashFlow:'Flujo de caja anual', cashOnCash:'Rentabilidad sobre capital aportado',
        payback:'Periodo de recuperación', years:'años', irrNoConverge:'— (supuestos demasiado extremos para calcular)', disclaimer:'Estimación basada exclusivamente en los valores introducidos — Z Find no calcula ni garantiza la rentabilidad. Confirme el tipo de IRS aplicable y los costes de adquisición con un asesor antes de decidir.',
      },
      zone: {
        notFound:'No se ha podido encontrar esta zona.', seeAllLink:'Ver todas las oportunidades actuales →',
        statsSummary:'{{count}} oportunidades actualmente publicadas · Precio medio {{avgPrice}}',
        thinInventory:'Z Find está incorporando activamente oportunidades en esta zona.',
      },
      hero: {
        eyebrow:'Portal inmobiliario internacional',
        titleLine1:'Explore oportunidades inmobiliarias en', titleLineEm:'mercados internacionales seleccionados.',
        lead:'Busque inmuebles, promociones y terrenos con menos duplicación, mayor contexto de mercado y acceso directo a los socios que los representan.',
        p1title:'Más oportunidades.\nMenos duplicación.', p1body:'Un activo real, un único registro canónico — independientemente de cuántos socios lo representen.',
        p2title:'Más información.\nMenos ruido.', p2body:'Contexto de mercado, datos urbanísticos y estimaciones claramente identificados — no cinco copias incoherentes del mismo anuncio.',
        p3title:'Más conexión.\nMenos fricción.', p3body:'Contacto directo cuando busca rapidez. Presentación cualificada cuando busca relevancia.',
      },
      language: { planned:'Próximamente' },
      market: {
        headerLabel:'Mercados', choose:'Explorar países y mercados', eyebrow:'Mercados internacionales',
        helper:'Elija un país o mercado para entrar en su marketplace Z Find.', browseMarkets:'Explorar países y mercados',
        aria:'Explorar marketplaces Z Find por país y mercado',
      },
      search: {
        tabResidential:'Residencial', tabCommercial:'Comercial', tabDevelopments:'Promociones', tabLand:'Terrenos y Desarrollo',
        locationPh:'Ubicación — ciudad, zona o dirección', anyType:'Cualquier tipo', anyBudget:'Cualquier presupuesto',
        buy:'Comprar', rent:'Alquilar', rentalPeriod:'Periodo de alquiler', monthly:'Mensual', seasonal:'Temporada', yearly:'Anual',
        priceFrom:'Desde', perMonth:'/mes', perSeason:'/temporada', perYear:'/año', forRent:'En alquiler',
        typeAny:'Cualquier tipo', typeApartment:'Apartamento', typeVilla:'Villa', typeOffice:'Oficina', typeRetail:'Comercial', typeIndustrialLogistics:'Industrial y Logística', typeHospitality:'Hostelería', typeDevelopment:'Promoción', typeLand:'Terreno',
        budgetUnder400:'Hasta 400.000 €', budget400to700:'400.000 € – 700.000 €', budgetOver700:'Más de 700.000 €',
        rentBudgetUnder1500:'Hasta 1.500 € / mes', rentBudget1500to2500:'1.500 € – 2.500 € / mes', rentBudget2500to4000:'2.500 € – 4.000 € / mes', rentBudgetOver4000:'Más de 4.000 € / mes',
        applyFilters:'Buscar', clearFilters:'Limpiar filtros',
        noResultsTitle:'Ninguna oportunidad coincide con estos filtros', noResultsBody:'Pruebe una ubicación más amplia, otra categoría o un rango de presupuesto mayor.',
        resultsTitle:'{{count}} oportunidades{{market}}', resultsSub:'Sin duplicados — cada ficha representa una oportunidad canónica distinta.',
        filterAll:'Todas', filterApartments:'Apartamentos', filterVillas:'Villas', filterCommercial:'Comercial', filterDevelopments:'Promociones', filterLand:'Terrenos',
      },
      home: {
        landTitle:'Inteligencia de terrenos y desarrollo', landSub:'Donde terminan los portales tradicionales, Z Find transforma fragmentos en inteligencia estructurada sobre oportunidades.',
        exploreLand:'Explorar oportunidades de terreno', loadingTitle:'Cargando oportunidades…', loadingBody:'Obteniendo los anuncios más recientes.',
        emptyTitle:'Se están incorporando nuevas oportunidades', emptyBody:'Explore nuestros mercados internacionales mientras se publican nuevos anuncios.',
        errorTitle:'No hemos podido cargar los anuncios', errorBody:'Vuelva a intentarlo en unos instantes.',
      },
      property: {
        aboutTitle:'Sobre esta oportunidad', marketTitle:'Ubicación y contexto de mercado', investmentTitle:'Potencial de inversión',
        zIntelComingSoonBody:'El análisis de mercado de Z Intelligence para esta oportunidad estará disponible en una futura versión.', zInsightsTitle:'Z Insights',
        zInsightsComingSoonBody:'Los análisis profesionales y observaciones de contexto para esta oportunidad estarán disponibles en una futura versión.',
        zIntelInvestmentComingSoonBody:'La puntuación de inversión de Z Intelligence para esta oportunidad estará disponible en una futura versión.', trustComingSoon:'Índice de Confianza — Próximamente',
        typology:'Tipología', grossArea:'Superficie bruta', energyRating:'Calificación energética', bathrooms:'Baños', parking:'Aparcamiento', yearBuilt:'Año de construcción',
        avgPriceZone:'Media €/m² — zona', priceThis:'Esta oportunidad', trend12m:'Tendencia de precio 12 meses, zona', comparables:'Operaciones comparables (6 meses)',
        estYield:'Rentabilidad estimada', estRent:'Alquiler mensual estimado', yieldSimTitle:'Simulador de rentabilidad', purchasePrice:'Precio de compra', estCosts:'Costes de transacción estimados (~7 %)', estAnnualRent:'Alquiler anual estimado', estGrossYield:'Rentabilidad bruta estimada',
        unitEnquireLabel:'Consultar', representedBy:'Representado por', contactBtn:'Contactar sobre esta oportunidad', saveBtn:'Guardar oportunidad',
        singleRepresentation:'Representación única verificada', previouslyRepresented:'Anteriormente representado por {{partner}} ({{start}}–{{end}})', nowRepresented:'Representado actualmente por {{partner}} desde {{start}}',
        notFoundTitle:'Este anuncio ya no está disponible', notFoundBody:'Puede haberse vendido, retirado o el enlace puede ser incorrecto.',
      },
      development: {
        developer:'Promotor', completion:'Finalización', units:'Unidades', typologies:'Tipologías', construction:'Construcción', amenities:'Servicios',
        availableUnits:'Unidades disponibles', colUnit:'Unidad', colTypology:'Tipología', colArea:'Superficie', colFloor:'Planta', colPrice:'Precio', colStatus:'Estado',
        view:'Ver', enquireBtn:'Consultar sobre esta promoción', brochureBtn:'Descargar folleto', statusAvailable:'Disponible', statusReserved:'Reservada', statusSold:'Vendida', totalUnits:'{{n}} en total',
        unitDetailTitle:'Unidad {{unit}}', enquireAboutUnit:'Consultar sobre esta unidad', closeUnit:'Cerrar', unitNotAvailable:'Esta unidad ya no está disponible para consultas.',
      },
      land: {
        knownFacts:'Datos conocidos', planningContext:'Contexto urbanístico', scenarios:'Posibles escenarios de desarrollo', jumpKnownFacts:'Datos conocidos', jumpPlanning:'Contexto urbanístico', jumpScenarios:'Escenarios',
        plotArea:'Superficie de parcela', currentUse:'Uso actual', zoning:'Zonificación (PDM)', access:'Acceso', estBuildableGBA:'Edificabilidad bruta estimada', estMaxHeight:'Altura máxima estimada', pipStatus:'Estado del PIP',
        planningDisclaimer:'Las estimaciones urbanísticas se basan en la zonificación del PDM y en aprobaciones comparables cercanas — no constituyen una determinación urbanística confirmada. Se recomienda un PIP formal o una consulta urbanística antes de adquirir.',
        scenarioDisclaimer:'Los escenarios son resultados ilustrativos de modelo para apoyar una evaluación inicial; no son estudios de viabilidad ni garantías de aprobación, coste o rentabilidad.',
        scenarioResidential:'Escenario A — Residencial', scenarioMixedUse:'Escenario B — Uso mixto', scenarioResidentialDesc:'~{{units}} apartamentos (T1–T3), coste de construcción estimado {{cost}}, plazo estimado de {{months}} meses.',
        scenarioMixedDesc:'Locales comerciales en planta baja + apartamentos, mayor rentabilidad estimada y tramitación más compleja.', estGDV:'GDV est. {{value}}',
        relevantProfessionals:'Profesionales relevantes', requestNetwork:'Solicitar red profesional', planningConsultant:'Consultor urbanístico', architect:'Arquitecto (uso mixto)', availableOnRequest:'Disponible bajo solicitud',
        matchingTitle:'Conexión con inversor / promotor', matchingBody:'Esta oportunidad admite presentaciones cualificadas de inversores y promotores.', expressInterest:'Manifestar interés',
        vacantFormerIndustrial:'Vacante, antiguo uso industrial', mixedUseUrban:'Urbano de uso mixto', pavedRoad:'Vía pavimentada, servicios cercanos', notSubmitted:'Aún no presentado', sixFloors:'6 plantas',
      },
      trust: { levelHigh:'Nivel de confianza: Alto', levelEstablished:'Nivel de confianza: Establecido', levelLimited:'Nivel de confianza: Limitado', why:'Por qué', limitations:'Limitaciones', evidence:'Evidencia' },
      dataStatus: { fact:'Hecho', observation:'Observación', estimate:'Estimación', modelOutput:'Resultado de modelo', professionalInterpretation:'Interpretación profesional', legalDetermination:'Determinación jurídica', data:'Datos' },
      partner: {
        activeOpportunities:'Oportunidades activas', developments:'Promociones', landOpportunities:'Oportunidades de terreno', avgResponse:'Tiempo medio de respuesta',
        filterAll:'Todas ({{n}})', filterResidential:'Residencial ({{n}})', filterDevelopments:'Promociones ({{n}})', filterLand:'Terrenos ({{n}})',
        unavailableTitle:'Socio no disponible', unavailableBody:'Este perfil de socio no está disponible o no tiene oportunidades públicas.', noOpportunities:'No hay oportunidades activas disponibles.',
      },
      enquiry: {
        title:'¿Cómo desea ponerse en contacto?', sub:'Este anunciante acepta contacto directo y cualificado. Elija la opción que más le convenga.',
        directTitle:'Contacto directo', directBody:'Escriba al anunciante de inmediato. La opción más rápida, sin preguntas de cualificación.', noForms:'Sin formularios',
        qualifiedTitle:'Presentación cualificada', qualifiedBody:'Responda unas breves preguntas para que el anunciante comprenda su interés antes de hablar — normalmente mejora la primera conversación.', recommended:'Recomendado',
        lookingFor:'¿Qué busca?', ownUse:'Comprar para uso propio', investment:'Comprar como inversión', exploring:'Solo explorando', budgetRange:'Rango de presupuesto', timing:'Plazo', within3:'En los próximos 3 meses', months3to6:'3–6 meses', noTimeline:'Explorando, sin plazo',
        yourName:'Su nombre', fullName:'Nombre completo', emailLabel:'Correo electrónico', emailPh:'usted@ejemplo.com', phoneLabel:'Teléfono', phonePh:'+351 900 000 000', atLeastOneNote:'Indique al menos uno — correo electrónico o teléfono.',
        send:'Enviar presentación', privacyNote:'Su información solo se comparte con este anunciante y para esta oportunidad.', sending:'Enviando…', submitSuccess:'Gracias — su consulta ha sido enviada. El anunciante se pondrá en contacto con usted en breve.',
        submitError:'Se ha producido un error y su consulta no se ha enviado. Vuelva a intentarlo en unos instantes.', validationError:'Indique su nombre y un correo electrónico o teléfono válido para que el anunciante pueda contactar con usted.',
        directOnlyNote:'Este anunciante acepta actualmente solo contacto directo.', qualifiedOnlyNote:'Esta oportunidad solo está disponible mediante una presentación cualificada — el anunciante lo ha solicitado por discreción o relevancia.',
        assistedTitle:'Consulta asistida', assistedBody:'El equipo de Z Find le ayudará personalmente a dirigir su consulta al contacto adecuado.', assistedOnlyNote:'Esta oportunidad se gestiona únicamente mediante consulta asistida — nuestro equipo dirigirá personalmente su solicitud.',
        landTemporarilyUnavailable:'Las consultas directas sobre terrenos estarán disponibles próximamente. Vuelva a consultarlo en breve.',
      },
      footer: { tagline:'De A a Z. Encontramos.', discover:'Descubrir', partners:'Socios', servicesLevels:'Niveles de servicio', partnerNetwork:'Red de socios', zos:'Z Operating System', trustProvenance:'Confianza y procedencia', howVerified:'Cómo se verifican las oportunidades', rights:'© 2026 Z Find — desarrollado sobre Z Operating System', location:'Porto, Portugal', contact:'Contacto', chatWhatsApp:'Hablar por WhatsApp', legalGuide:'Guía Jurídica', alManual:'Guía de Alquiler de Corta Duración' },
    },

    de: {
      common: { search:'Suchen', viewAll:'Alle ansehen', save:'Speichern', signIn:'Anmelden', publish:'Portfolio veröffentlichen', close:'Schließen', backToResults:'← Zurück zu den Suchergebnissen' },
      navigation: { home:'Start', search:'Suchen', property:'Immobilie', development:'Neubauprojekt', land:'Grundstücke & Entwicklung', partner:'Partner', simulator:'Rechner' },
      simulator: { title:'Kaufnebenkosten-Rechner', subtitle:'Schätzen Sie Grunderwerbsteuer (IMT) und Stempelsteuer beim Immobilienkauf in Portugal.', country:'Land', propertyValue:'Immobilienwert (€)', isHPP:'Dies wird mein Hauptwohnsitz', isResident:'Ich bin in Portugal steuerlich ansässig', calculate:'Berechnen', imt:'Grunderwerbsteuer (IMT)', stampDuty:'Stempelsteuer', total:'Gesamt', tabCosts:'Kaufnebenkosten', tabYield:'Mietrendite' },
      yieldSim: {
        title:'Mietrendite-Rechner', subtitle:'Geben Sie Ihre eigenen Annahmen ein — dieses Werkzeug berechnet sie lediglich und schätzt niemals eine Rendite für Sie.', modeAL:'Kurzzeitvermietung (Alojamento Local)', modeALD:'Langzeitvermietung',
        propertyValue:'Immobilienwert (€)', renovation:'Renovierungskosten (€)', acquisitionCosts:'Kaufnebenkosten — IMT + Stempelsteuer (€)', acquisitionCostsNote:'Diesen Betrag erhalten Sie im', acquisitionCostsLink:'Kaufnebenkosten-Rechner →',
        dailyRate:'Tagessatz (€)', occupancy:'Auslastung (%)', platformFee:'Plattformgebühr (%)', managementFee:'Verwaltungsgebühr (%)', utilitiesMonthly:'Nebenkosten — monatlich (€)', monthlyRent:'Monatsmiete (€)', voidMonths:'Leerstandsmonate / Jahr',
        condoMonthly:'Hausgeld — monatlich (€)', irsRate:'IRS-Steuersatz auf Mieteinnahmen (%)', irsRateNote:'Der reguläre Pauschalsatz beträgt 28 % — klären Sie den für Ihre Situation geltenden Satz mit einem Steuerberater; langfristige Verträge können Ermäßigungen erhalten.',
        hasLoan:'Mit Darlehen finanziert', loanAmount:'Darlehensbetrag (€)', loanRate:'Darlehenszins (%)', loanYears:'Darlehenslaufzeit (Jahre)', calculate:'Berechnen', grossYield:'Bruttorendite', netYield:'Nettorendite', cashFlow:'Jährlicher Cashflow', cashOnCash:'Cash-on-Cash-Rendite',
        payback:'Amortisationsdauer', years:'Jahre', irrNoConverge:'— (Annahmen zu extrem für eine Berechnung)', disclaimer:'Die Schätzung basiert ausschließlich auf Ihren Eingaben — Z Find berechnet oder garantiert keine Rentabilität. Bestätigen Sie den geltenden IRS-Satz und die Kaufnebenkosten mit einem Steuerberater oder Berater, bevor Sie entscheiden.'
      },
      zone: { notFound:'Diese Zone wurde nicht gefunden.', seeAllLink:'Alle aktuellen Angebote ansehen →', statsSummary:'{{count}} aktuell gelistete Angebote · Durchschnittspreis {{avgPrice}}', thinInventory:'Z Find ergänzt derzeit aktiv Angebote in dieser Zone.' },
      hero: { eyebrow:'Internationales Immobilienportal', titleLine1:'Entdecken Sie Immobilienchancen in', titleLineEm:'ausgewählten internationalen Märkten.', lead:'Suchen Sie Immobilien, Neubauprojekte und Grundstücke mit weniger Duplikaten, mehr Marktkontext und direktem Zugang zu den vertretenden Partnern.', p1title:'Mehr Chancen.\nWeniger Duplikate.', p1body:'Ein reales Objekt, ein kanonischer Datensatz — unabhängig davon, wie viele Partner es vertreten.', p2title:'Mehr Information.\nWeniger Rauschen.', p2body:'Marktkontext, Planungsfakten und Schätzungen klar gekennzeichnet — statt fünf widersprüchlicher Kopien desselben Angebots.', p3title:'Mehr Verbindung.\nWeniger Reibung.', p3body:'Direkter Kontakt, wenn Geschwindigkeit zählt. Qualifizierte Einführung, wenn Relevanz zählt.' },
      language: { planned:'Demnächst' },
      market: { headerLabel:'Märkte', choose:'Länder & Märkte entdecken', eyebrow:'Internationale Märkte', helper:'Wählen Sie ein Land oder einen Markt, um dessen Z Find Marketplace zu öffnen.', browseMarkets:'Länder & Märkte entdecken', aria:'Z Find Marketplaces nach Land und Markt entdecken' },
      search: {
        tabResidential:'Wohnen', tabCommercial:'Gewerbe', tabDevelopments:'Neubauprojekte', tabLand:'Grundstücke & Entwicklung', locationPh:'Ort — Stadt, Gebiet oder Adresse', anyType:'Alle Typen', anyBudget:'Jedes Budget', buy:'Kaufen', rent:'Mieten', rentalPeriod:'Mietzeitraum', monthly:'Monatlich', seasonal:'Saisonal', yearly:'Jährlich', priceFrom:'Ab', perMonth:'/Monat', perSeason:'/Saison', perYear:'/Jahr', forRent:'Zu vermieten',
        typeAny:'Alle Typen', typeApartment:'Wohnung', typeVilla:'Villa', typeOffice:'Büro', typeRetail:'Einzelhandel', typeIndustrialLogistics:'Industrie & Logistik', typeHospitality:'Hotellerie', typeDevelopment:'Neubauprojekt', typeLand:'Grundstück',
        budgetUnder400:'Bis 400.000 €', budget400to700:'400.000 € – 700.000 €', budgetOver700:'Über 700.000 €', rentBudgetUnder1500:'Bis 1.500 € / Monat', rentBudget1500to2500:'1.500 € – 2.500 € / Monat', rentBudget2500to4000:'2.500 € – 4.000 € / Monat', rentBudgetOver4000:'Über 4.000 € / Monat',
        applyFilters:'Suchen', clearFilters:'Filter löschen', noResultsTitle:'Keine Angebote entsprechen diesen Filtern', noResultsBody:'Versuchen Sie einen größeren Suchbereich, eine andere Kategorie oder ein breiteres Budget.', resultsTitle:'{{count}} Angebote{{market}}', resultsSub:'Ohne Duplikate — jede Karte steht für eine eigene kanonische Gelegenheit.', filterAll:'Alle', filterApartments:'Wohnungen', filterVillas:'Villen', filterCommercial:'Gewerbe', filterDevelopments:'Neubauprojekte', filterLand:'Grundstücke'
      },
      home: { landTitle:'Intelligence für Grundstücke & Entwicklung', landSub:'Wo traditionelle Portale aufhören, macht Z Find aus Fragmenten strukturierte Chancen-Intelligence.', exploreLand:'Grundstückschancen entdecken', loadingTitle:'Angebote werden geladen…', loadingBody:'Die neuesten Angebote werden abgerufen.', emptyTitle:'Neue Angebote werden hinzugefügt', emptyBody:'Entdecken Sie unsere internationalen Märkte, während neue Angebote online gehen.', errorTitle:'Angebote konnten nicht geladen werden', errorBody:'Bitte versuchen Sie es gleich noch einmal.' },
      property: {
        aboutTitle:'Über diese Gelegenheit', marketTitle:'Lage & Marktkontext', investmentTitle:'Investitionspotenzial', zIntelComingSoonBody:'Die Z Intelligence Marktanalyse für diese Gelegenheit wird in einer künftigen Version verfügbar sein.', zInsightsTitle:'Z Insights', zInsightsComingSoonBody:'Professionelle Einblicke und kontextbezogene Beobachtungen für diese Gelegenheit werden in einer künftigen Version verfügbar sein.', zIntelInvestmentComingSoonBody:'Das Z Intelligence Investment-Scoring für diese Gelegenheit wird in einer künftigen Version verfügbar sein.', trustComingSoon:'Vertrauensindex — Demnächst',
        typology:'Typologie', grossArea:'Bruttofläche', energyRating:'Energieklasse', bathrooms:'Bäder', parking:'Stellplätze', yearBuilt:'Baujahr', avgPriceZone:'Durchschnitt €/m² — Gebiet', priceThis:'Diese Gelegenheit', trend12m:'12-Monats-Preistrend, Gebiet', comparables:'Vergleichstransaktionen (6 Mon.)', estYield:'Geschätzte Mietrendite', estRent:'Geschätzte Monatsmiete', yieldSimTitle:'Rendite-Rechner', purchasePrice:'Kaufpreis', estCosts:'Geschätzte Transaktionskosten (~7 %)', estAnnualRent:'Geschätzte Jahresmiete', estGrossYield:'Geschätzte Bruttorendite', unitEnquireLabel:'Anfragen', representedBy:'Vertreten durch', contactBtn:'Zu dieser Gelegenheit Kontakt aufnehmen', saveBtn:'Gelegenheit speichern', singleRepresentation:'Einzige verifizierte Vertretung', previouslyRepresented:'Zuvor vertreten durch {{partner}} ({{start}}–{{end}})', nowRepresented:'Seit {{start}} vertreten durch {{partner}}', notFoundTitle:'Dieses Angebot ist nicht mehr verfügbar', notFoundBody:'Es wurde möglicherweise verkauft, zurückgezogen oder der Link ist fehlerhaft.'
      },
      development: { developer:'Bauträger', completion:'Fertigstellung', units:'Einheiten', typologies:'Typologien', construction:'Bau', amenities:'Ausstattung', availableUnits:'Verfügbare Einheiten', colUnit:'Einheit', colTypology:'Typologie', colArea:'Fläche', colFloor:'Etage', colPrice:'Preis', colStatus:'Status', view:'Ansehen', enquireBtn:'Zu diesem Neubauprojekt anfragen', brochureBtn:'Broschüre herunterladen', statusAvailable:'Verfügbar', statusReserved:'Reserviert', statusSold:'Verkauft', totalUnits:'{{n}} insgesamt', unitDetailTitle:'Einheit {{unit}}', enquireAboutUnit:'Zu dieser Einheit anfragen', closeUnit:'Schließen', unitNotAvailable:'Diese Einheit ist nicht mehr für Anfragen verfügbar.' },
      land: {
        knownFacts:'Bekannte Fakten', planningContext:'Planungskontext', scenarios:'Mögliche Entwicklungsszenarien', jumpKnownFacts:'Bekannte Fakten', jumpPlanning:'Planungskontext', jumpScenarios:'Szenarien', plotArea:'Grundstücksfläche', currentUse:'Aktuelle Nutzung', zoning:'Bauleitplanung (PDM)', access:'Zufahrt', estBuildableGBA:'Geschätzte bebaubare Bruttogeschossfläche', estMaxHeight:'Geschätzte maximale Höhe', pipStatus:'PIP-Status',
        planningDisclaimer:'Planungsschätzungen beruhen auf PDM-Zonierung und vergleichbaren Genehmigungen in der Umgebung — sie sind keine bestätigte planungsrechtliche Entscheidung. Vor dem Erwerb wird ein formelles PIP oder eine Planungsberatung empfohlen.', scenarioDisclaimer:'Die Szenarien sind illustrative Modellergebnisse zur frühen Bewertung, keine Machbarkeitsstudien oder Garantien für Genehmigung, Kosten oder Rendite.', scenarioResidential:'Szenario A — Wohnen', scenarioMixedUse:'Szenario B — Mischnutzung', scenarioResidentialDesc:'~{{units}} Wohnungen (T1–T3), geschätzte Baukosten {{cost}}, geschätzte Bauzeit {{months}} Monate.', scenarioMixedDesc:'Einzelhandel im Erdgeschoss + Wohnungen, höhere geschätzte Rendite, komplexerer Genehmigungsweg.', estGDV:'GDV geschätzt {{value}}', relevantProfessionals:'Relevante Fachleute', requestNetwork:'Passendes Netzwerk anfragen', planningConsultant:'Planungsberater', architect:'Architekt (Mischnutzung)', availableOnRequest:'Auf Anfrage verfügbar', matchingTitle:'Investor-/Entwickler-Matching', matchingBody:'Diese Gelegenheit ist offen für qualifizierte Einführungen von Investoren und Entwicklern.', expressInterest:'Interesse bekunden', vacantFormerIndustrial:'Leerstehend, ehemals industriell', mixedUseUrban:'Urbanes Mischgebiet', pavedRoad:'Befestigte Straße, Versorgungsleitungen in der Nähe', notSubmitted:'Noch nicht eingereicht', sixFloors:'6 Etagen'
      },
      trust: { levelHigh:'Vertrauensniveau: Hoch', levelEstablished:'Vertrauensniveau: Etabliert', levelLimited:'Vertrauensniveau: Begrenzt', why:'Warum', limitations:'Einschränkungen', evidence:'Nachweise' },
      dataStatus: { fact:'Fakt', observation:'Beobachtung', estimate:'Schätzung', modelOutput:'Modellergebnis', professionalInterpretation:'Professionelle Interpretation', legalDetermination:'Rechtliche Feststellung', data:'Daten' },
      partner: { activeOpportunities:'Aktive Angebote', developments:'Neubauprojekte', landOpportunities:'Grundstückschancen', avgResponse:'Durchschn. Antwortzeit', filterAll:'Alle ({{n}})', filterResidential:'Wohnen ({{n}})', filterDevelopments:'Neubauprojekte ({{n}})', filterLand:'Grundstücke ({{n}})', unavailableTitle:'Partner nicht verfügbar', unavailableBody:'Dieses Partnerprofil ist nicht verfügbar oder hat keine öffentlichen Angebote.', noOpportunities:'Keine aktiven Angebote verfügbar.' },
      enquiry: {
        title:'Wie möchten Sie Kontakt aufnehmen?', sub:'Dieser Anbieter akzeptiert direkten und qualifizierten Kontakt. Wählen Sie die passende Option.', directTitle:'Direkter Kontakt', directBody:'Schreiben Sie dem Anbieter sofort. Schnellste Option, ohne Qualifizierungsfragen.', noForms:'Keine Formulare', qualifiedTitle:'Qualifizierte Einführung', qualifiedBody:'Beantworten Sie einige kurze Fragen, damit der Anbieter Ihr Interesse vor dem Gespräch versteht — meist die bessere erste Unterhaltung.', recommended:'Empfohlen', lookingFor:'Was suchen Sie?', ownUse:'Kauf zur Eigennutzung', investment:'Kauf als Investment', exploring:'Nur erkunden', budgetRange:'Budgetrahmen', timing:'Zeitrahmen', within3:'Innerhalb von 3 Monaten', months3to6:'3–6 Monate', noTimeline:'Erkundung, kein Zeitplan', yourName:'Ihr Name', fullName:'Vollständiger Name', emailLabel:'E-Mail', emailPh:'sie@beispiel.de', phoneLabel:'Telefon', phonePh:'+351 900 000 000', atLeastOneNote:'Geben Sie mindestens eines an — E-Mail oder Telefon.', send:'Einführung senden', privacyNote:'Ihre Angaben werden nur für diese Gelegenheit mit diesem Anbieter geteilt.', sending:'Wird gesendet…', submitSuccess:'Vielen Dank — Ihre Anfrage wurde gesendet. Der Anbieter wird Sie in Kürze kontaktieren.', submitError:'Es ist ein Fehler aufgetreten und Ihre Anfrage wurde nicht gesendet. Bitte versuchen Sie es gleich noch einmal.', validationError:'Bitte geben Sie Ihren Namen und eine gültige E-Mail-Adresse oder Telefonnummer an, damit der Anbieter Sie erreichen kann.', directOnlyNote:'Dieser Anbieter akzeptiert derzeit nur direkten Kontakt.', qualifiedOnlyNote:'Diese Gelegenheit ist nur über eine qualifizierte Einführung verfügbar — der Anbieter wünscht dies aus Diskretions- oder Relevanzgründen.', assistedTitle:'Betreute Anfrage', assistedBody:'Das Z Find Team hilft Ihnen persönlich, Ihre Anfrage an den richtigen Kontakt zu leiten.', assistedOnlyNote:'Diese Gelegenheit wird ausschließlich als betreute Anfrage bearbeitet — unser Team leitet Ihre Anfrage persönlich weiter.', landTemporarilyUnavailable:'Direkte Anfragen zu Grundstückschancen sind demnächst verfügbar. Bitte schauen Sie bald wieder vorbei.'
      },
      footer: { tagline:'Von A bis Z. Wir finden.', discover:'Entdecken', partners:'Partner', servicesLevels:'Servicelevel', partnerNetwork:'Partnernetzwerk', zos:'Z Operating System', trustProvenance:'Vertrauen & Herkunft', howVerified:'Wie Angebote verifiziert werden', rights:'© 2026 Z Find — auf dem Z Operating System aufgebaut', location:'Porto, Portugal', contact:'Kontakt', chatWhatsApp:'Über WhatsApp chatten', legalGuide:'Rechtsleitfaden', alManual:'Leitfaden Kurzzeitvermietung' }
    },

    it: {
      common: { search:'Cerca', viewAll:'Vedi tutto', save:'Salva', signIn:'Accedi', publish:'Pubblica il tuo portafoglio', close:'Chiudi', backToResults:'← Torna ai risultati' },
      navigation: { home:'Home', search:'Cerca', property:'Immobile', development:'Nuova costruzione', land:'Terreni e Sviluppo', partner:'Partner', simulator:'Simulatori' },
      simulator: { title:'Simulatore dei Costi di Acquisto', subtitle:'Stima l’imposta di trasferimento (IMT) e l’imposta di bollo per l’acquisto di una casa in Portogallo.', country:'Paese', propertyValue:'Valore dell’immobile (€)', isHPP:'Questa sarà la mia residenza principale', isResident:'Sono residente fiscale in Portogallo', calculate:'Calcola', imt:'Imposta di trasferimento (IMT)', stampDuty:'Imposta di bollo', total:'Totale', tabCosts:'Costi di Acquisto', tabYield:'Rendimento' },
      yieldSim: {
        title:'Simulatore di Rendimento', subtitle:'Inserisci le tue ipotesi — questo strumento esegue i calcoli, senza mai stimare un rendimento al posto tuo.', modeAL:'Breve termine (Alojamento Local)', modeALD:'Locazione a lungo termine', propertyValue:'Valore dell’immobile (€)', renovation:'Costi di ristrutturazione (€)', acquisitionCosts:'Costi di acquisto — IMT + Imposta di bollo (€)', acquisitionCostsNote:'Ottieni questo valore dal', acquisitionCostsLink:'Simulatore dei Costi di Acquisto →', dailyRate:'Tariffa giornaliera (€)', occupancy:'Occupazione (%)', platformFee:'Commissione piattaforma (%)', managementFee:'Commissione di gestione (%)', utilitiesMonthly:'Utenze — mensili (€)', monthlyRent:'Canone mensile (€)', voidMonths:'Mesi sfitti / anno', condoMonthly:'Condominio — mensile (€)', irsRate:'Aliquota IRS sui redditi da locazione (%)', irsRateNote:'L’aliquota ordinaria è del 28% — verifica con un consulente fiscale l’aliquota applicabile alla tua situazione; i contratti di lunga durata possono beneficiare di riduzioni.', hasLoan:'Finanziato con mutuo', loanAmount:'Importo del mutuo (€)', loanRate:'Tasso del mutuo (%)', loanYears:'Durata del mutuo (anni)', calculate:'Calcola', grossYield:'Rendimento lordo', netYield:'Rendimento netto', cashFlow:'Flusso di cassa annuo', cashOnCash:'Rendimento cash-on-cash', payback:'Periodo di recupero', years:'anni', irrNoConverge:'— (ipotesi troppo estreme per il calcolo)', disclaimer:'Stima basata esclusivamente sui valori inseriti — Z Find non calcola né garantisce la redditività. Verifica l’aliquota IRS applicabile e i costi di acquisto con un commercialista o consulente prima di decidere.'
      },
      zone: { notFound:'Questa zona non è stata trovata.', seeAllLink:'Vedi tutte le opportunità attuali →', statsSummary:'{{count}} opportunità attualmente pubblicate · Prezzo medio {{avgPrice}}', thinInventory:'Z Find sta aggiungendo attivamente opportunità in questa zona.' },
      hero: { eyebrow:'Portale immobiliare internazionale', titleLine1:'Esplora opportunità immobiliari in', titleLineEm:'mercati internazionali selezionati.', lead:'Cerca immobili, nuove costruzioni e terreni con meno duplicazioni, più contesto di mercato e accesso diretto ai partner che li rappresentano.', p1title:'Più opportunità.\nMeno duplicazioni.', p1body:'Un bene reale, un unico record canonico — indipendentemente dal numero di partner che lo rappresentano.', p2title:'Più informazioni.\nMeno rumore.', p2body:'Contesto di mercato, dati urbanistici e stime chiaramente identificati — non cinque copie incoerenti dello stesso annuncio.', p3title:'Più connessione.\nMeno attrito.', p3body:'Contatto diretto quando vuoi velocità. Introduzione qualificata quando vuoi pertinenza.' },
      language: { planned:'Prossimamente' },
      market: { headerLabel:'Mercati', choose:'Esplora paesi e mercati', eyebrow:'Mercati internazionali', helper:'Scegli un paese o un mercato per entrare nel relativo marketplace Z Find.', browseMarkets:'Esplora paesi e mercati', aria:'Esplora i marketplace Z Find per paese e mercato' },
      search: { tabResidential:'Residenziale', tabCommercial:'Commerciale', tabDevelopments:'Nuove costruzioni', tabLand:'Terreni e Sviluppo', locationPh:'Località — città, zona o indirizzo', anyType:'Qualsiasi tipo', anyBudget:'Qualsiasi budget', buy:'Acquista', rent:'Affitta', rentalPeriod:'Periodo di locazione', monthly:'Mensile', seasonal:'Stagionale', yearly:'Annuale', priceFrom:'Da', perMonth:'/mese', perSeason:'/stagione', perYear:'/anno', forRent:'In affitto', typeAny:'Qualsiasi tipo', typeApartment:'Appartamento', typeVilla:'Villa', typeOffice:'Ufficio', typeRetail:'Retail', typeIndustrialLogistics:'Industriale e Logistica', typeHospitality:'Ospitalità', typeDevelopment:'Nuova costruzione', typeLand:'Terreno', budgetUnder400:'Fino a 400.000 €', budget400to700:'400.000 € – 700.000 €', budgetOver700:'Oltre 700.000 €', rentBudgetUnder1500:'Fino a 1.500 € / mese', rentBudget1500to2500:'1.500 € – 2.500 € / mese', rentBudget2500to4000:'2.500 € – 4.000 € / mese', rentBudgetOver4000:'Oltre 4.000 € / mese', applyFilters:'Cerca', clearFilters:'Azzera filtri', noResultsTitle:'Nessuna opportunità corrisponde a questi filtri', noResultsBody:'Prova una località più ampia, una categoria diversa o una fascia di budget più estesa.', resultsTitle:'{{count}} opportunità{{market}}', resultsSub:'Senza duplicati — ogni scheda rappresenta una distinta opportunità canonica.', filterAll:'Tutte', filterApartments:'Appartamenti', filterVillas:'Ville', filterCommercial:'Commerciale', filterDevelopments:'Nuove costruzioni', filterLand:'Terreni' },
      home: { landTitle:'Intelligence per terreni e sviluppo', landSub:'Dove i portali tradizionali si fermano, Z Find trasforma frammenti in intelligence strutturata sulle opportunità.', exploreLand:'Esplora opportunità di terreno', loadingTitle:'Caricamento opportunità…', loadingBody:'Recupero degli annunci più recenti.', emptyTitle:'Stiamo aggiungendo nuove opportunità', emptyBody:'Esplora i nostri mercati internazionali mentre arrivano nuovi annunci.', errorTitle:'Impossibile caricare gli annunci', errorBody:'Riprova tra qualche istante.' },
      property: { aboutTitle:'Informazioni su questa opportunità', marketTitle:'Posizione e contesto di mercato', investmentTitle:'Potenziale di investimento', zIntelComingSoonBody:'L’analisi di mercato Z Intelligence per questa opportunità sarà disponibile in una prossima versione.', zInsightsTitle:'Z Insights', zInsightsComingSoonBody:'Approfondimenti professionali e osservazioni contestuali su questa opportunità saranno disponibili in una prossima versione.', zIntelInvestmentComingSoonBody:'Il punteggio di investimento Z Intelligence per questa opportunità sarà disponibile in una prossima versione.', trustComingSoon:'Indice di Affidabilità — Prossimamente', typology:'Tipologia', grossArea:'Superficie lorda', energyRating:'Classe energetica', bathrooms:'Bagni', parking:'Parcheggio', yearBuilt:'Anno di costruzione', avgPriceZone:'Media €/m² — zona', priceThis:'Questa opportunità', trend12m:'Trend prezzo 12 mesi, zona', comparables:'Transazioni comparabili (6 mesi)', estYield:'Rendimento locativo stimato', estRent:'Canone mensile stimato', yieldSimTitle:'Simulatore di rendimento', purchasePrice:'Prezzo di acquisto', estCosts:'Costi di transazione stimati (~7%)', estAnnualRent:'Canone annuo stimato', estGrossYield:'Rendimento lordo stimato', unitEnquireLabel:'Richiedi informazioni', representedBy:'Rappresentato da', contactBtn:'Contatta per questa opportunità', saveBtn:'Salva opportunità', singleRepresentation:'Rappresentanza unica verificata', previouslyRepresented:'In precedenza rappresentato da {{partner}} ({{start}}–{{end}})', nowRepresented:'Attualmente rappresentato da {{partner}} dal {{start}}', notFoundTitle:'Questo annuncio non è più disponibile', notFoundBody:'Potrebbe essere stato venduto, ritirato oppure il link potrebbe non essere corretto.' },
      development: { developer:'Promotore', completion:'Consegna', units:'Unità', typologies:'Tipologie', construction:'Costruzione', amenities:'Servizi', availableUnits:'Unità disponibili', colUnit:'Unità', colTypology:'Tipologia', colArea:'Superficie', colFloor:'Piano', colPrice:'Prezzo', colStatus:'Stato', view:'Vedi', enquireBtn:'Richiedi informazioni su questa nuova costruzione', brochureBtn:'Scarica brochure', statusAvailable:'Disponibile', statusReserved:'Riservata', statusSold:'Venduta', totalUnits:'{{n}} totali', unitDetailTitle:'Unità {{unit}}', enquireAboutUnit:'Richiedi informazioni su questa unità', closeUnit:'Chiudi', unitNotAvailable:'Questa unità non è più disponibile per richieste.' },
      land: { knownFacts:'Dati noti', planningContext:'Contesto urbanistico', scenarios:'Possibili scenari di sviluppo', jumpKnownFacts:'Dati noti', jumpPlanning:'Contesto urbanistico', jumpScenarios:'Scenari', plotArea:'Superficie del lotto', currentUse:'Uso attuale', zoning:'Zonizzazione (PDM)', access:'Accesso', estBuildableGBA:'Superficie lorda edificabile stimata', estMaxHeight:'Altezza massima stimata', pipStatus:'Stato PIP', planningDisclaimer:'Le stime urbanistiche si basano sulla zonizzazione PDM e su autorizzazioni comparabili nelle vicinanze — non costituiscono una determinazione urbanistica confermata. Prima dell’acquisto è consigliato un PIP formale o una consulenza urbanistica.', scenarioDisclaimer:'Gli scenari sono risultati illustrativi di modello a supporto di una valutazione iniziale, non studi di fattibilità né garanzie di approvazione, costo o rendimento.', scenarioResidential:'Scenario A — Residenziale', scenarioMixedUse:'Scenario B — Uso misto', scenarioResidentialDesc:'~{{units}} appartamenti (T1–T3), costo di costruzione stimato {{cost}}, durata stimata dei lavori {{months}} mesi.', scenarioMixedDesc:'Retail al piano terra + appartamenti, rendimento stimato più elevato e iter autorizzativo più complesso.', estGDV:'GDV stimato {{value}}', relevantProfessionals:'Professionisti pertinenti', requestNetwork:'Richiedi rete professionale', planningConsultant:'Consulente urbanistico', architect:'Architetto (uso misto)', availableOnRequest:'Disponibile su richiesta', matchingTitle:'Matching investitore / promotore', matchingBody:'Questa opportunità è aperta a presentazioni qualificate di investitori e promotori.', expressInterest:'Esprimi interesse', vacantFormerIndustrial:'Libero, ex uso industriale', mixedUseUrban:'Urbano a uso misto', pavedRoad:'Strada asfaltata, utenze nelle vicinanze', notSubmitted:'Non ancora presentato', sixFloors:'6 piani' },
      trust: { levelHigh:'Livello di affidabilità: Alto', levelEstablished:'Livello di affidabilità: Consolidato', levelLimited:'Livello di affidabilità: Limitato', why:'Perché', limitations:'Limitazioni', evidence:'Evidenze' },
      dataStatus: { fact:'Fatto', observation:'Osservazione', estimate:'Stima', modelOutput:'Risultato del modello', professionalInterpretation:'Interpretazione professionale', legalDetermination:'Determinazione legale', data:'Dati' },
      partner: { activeOpportunities:'Opportunità attive', developments:'Nuove costruzioni', landOpportunities:'Opportunità di terreno', avgResponse:'Tempo medio di risposta', filterAll:'Tutte ({{n}})', filterResidential:'Residenziale ({{n}})', filterDevelopments:'Nuove costruzioni ({{n}})', filterLand:'Terreni ({{n}})', unavailableTitle:'Partner non disponibile', unavailableBody:'Questo profilo partner non è disponibile o non presenta opportunità pubbliche.', noOpportunities:'Nessuna opportunità attiva disponibile.' },
      enquiry: { title:'Come desideri entrare in contatto?', sub:'Questo inserzionista accetta contatti diretti e qualificati. Scegli l’opzione più adatta.', directTitle:'Contatto diretto', directBody:'Invia subito un messaggio all’inserzionista. È l’opzione più rapida, senza domande di qualificazione.', noForms:'Nessun modulo', qualifiedTitle:'Introduzione qualificata', qualifiedBody:'Rispondi a poche domande per permettere all’inserzionista di comprendere il tuo interesse prima di parlare — di solito migliora il primo contatto.', recommended:'Consigliato', lookingFor:'Cosa stai cercando?', ownUse:'Acquistare per uso personale', investment:'Acquistare come investimento', exploring:'Sto solo esplorando', budgetRange:'Fascia di budget', timing:'Tempistica', within3:'Entro 3 mesi', months3to6:'3–6 mesi', noTimeline:'Esplorazione, senza scadenza', yourName:'Il tuo nome', fullName:'Nome completo', emailLabel:'Email', emailPh:'tu@esempio.it', phoneLabel:'Telefono', phonePh:'+351 900 000 000', atLeastOneNote:'Indica almeno uno — email o telefono.', send:'Invia introduzione', privacyNote:'I tuoi dati vengono condivisi solo con questo inserzionista e per questa opportunità.', sending:'Invio in corso…', submitSuccess:'Grazie — la tua richiesta è stata inviata. L’inserzionista ti contatterà a breve.', submitError:'Si è verificato un errore e la richiesta non è stata inviata. Riprova tra qualche istante.', validationError:'Inserisci il tuo nome e un indirizzo email o un numero di telefono valido per permettere all’inserzionista di contattarti.', directOnlyNote:'Questo inserzionista accetta attualmente solo contatti diretti.', qualifiedOnlyNote:'Questa opportunità è disponibile solo tramite introduzione qualificata — l’inserzionista lo ha richiesto per discrezione o pertinenza.', assistedTitle:'Richiesta assistita', assistedBody:'Il team Z Find ti aiuterà personalmente a indirizzare la richiesta al contatto giusto.', assistedOnlyNote:'Questa opportunità viene gestita esclusivamente tramite richiesta assistita — il nostro team inoltrerà personalmente la tua richiesta.', landTemporarilyUnavailable:'Le richieste dirette per opportunità di terreno saranno disponibili prossimamente. Torna a breve.' },
      footer: { tagline:'Dalla A alla Z. Troviamo.', discover:'Scopri', partners:'Partner', servicesLevels:'Livelli di servizio', partnerNetwork:'Rete di partner', zos:'Z Operating System', trustProvenance:'Affidabilità e provenienza', howVerified:'Come vengono verificate le opportunità', rights:'© 2026 Z Find — costruito su Z Operating System', location:'Porto, Portogallo', contact:'Contatti', chatWhatsApp:'Chatta su WhatsApp', legalGuide:'Guida Legale', alManual:'Guida Locazioni Brevi' }
    }
  });

  const required = ['fr', 'en', 'pt', 'es', 'de', 'it'];
  for (const locale of required) {
    if (!I18N[locale]) throw new Error(`Missing complete Z Find UI translation: ${locale}`);
  }
})();
