-- ============================================================
-- Z Fashion — Baby Age Segment v1
-- Shared ZOS database (infrastructure/supabase)
--
-- Adds 'baby' as a fourth Age Segment, alongside children/youth/adults.
-- Mirrors the partner.js/product.js/onboarding.js change: baby is
-- genuinely distinct from children (different safety-certification
-- regime, different size conventions — pre-walking Footwear barely
-- exists as a real product line — never treated as a synonym for
-- "small child"). A new migration, not an edit to
-- 20260821090000_z_fashion_database_foundation_v1.sql — that migration
-- is already applied; Postgres enums and CHECK constraints are altered
-- forward, never rewritten in place.
--
-- This file adds the enum value ONLY. Postgres does not allow a new
-- enum value to be used (e.g. in a CHECK constraint) inside the same
-- transaction that added it (SQLSTATE 55P04, "unsafe use of new value
-- of enum type"). Each migration file is applied as its own
-- transaction, so the constraint that references 'baby' must live in
-- a separate, later-numbered migration file
-- (20260822021500_z_fashion_baby_age_segment_constraint_v1.sql) so the
-- ADD VALUE below is committed before anything uses it.
-- ============================================================

alter type fashion.age_segment add value if not exists 'baby';
